### ISSUE TITLE
Where's the contributing.md file?

### ISSUE THREAD

**Issue by sukhchainn** [BlenderNPR/BEER#1]
Hi,
Today I found out about blendernpr.org and from there I found about this project.
I want to contribute to this project, but I don't know from where to start. I am a C/C++ developer and I develop front-end and back-end. When I start to work on project I look for a contribute.md file which specifies the current progress and the details of features to be implemented, but it appears that work on this project hasn't started yet. I want to get started on this project and develop a prototype for an understanding of this project, but I don't know how exactly the project architecture should be and what to implement first.

Even in Milestones, there are "Foundational work" and "Layer UI" which doesn't make it easy to understand what "Foundational work" is and how "Layer UI" is supposed to interact with it.

If you can make a list of things that I should know before contributing to this project then it would be great. I am new to blender so if you want me to be knowledgeable in some concepts of it then please mention it in the contributing.md file. I really want to get started on this project and for that I need clear information as much as possible. If you make a resources section in contributing.md file then it would be enormously helpful.

Please help me understand the scope and goal of the project.

**Comment by Lateasusual** [comment]
Hi, 
General development discussion+planning is in the [bnpr discord](https://discord.gg/kzMWNqb), let Light know you're interested in helping out! 

The current iteration of the design doc is [here](https://www.pragma37.com/docs/npr/), but it will be easier to coordinate work in the discord server

**Comment by Lateasusual** [comment]
With that said, this info should probably be in the readme/contributing file, I agree
