### ISSUE TITLE
no opengl module?

### ISSUE THREAD

**Issue by AnityEx** [BlenderNPR/BEER#10]
I'm using a gtx 1060 3gb windows 10 with blender 2.9 official, and yes, i opened as administrator

this is the error:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\__init__.py", line 31, in <module>
    import Malt
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\__init__.py", line 3, in <module>
    from Malt import GL
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\GL.py", line 5, in <module>
    import OpenGL
ModuleNotFoundError: No module named 'OpenGL'
```
![image](https://user-images.githubusercontent.com/61922421/93293208-aa2d1580-f7a4-11ea-8fec-a9838603a3f7.png)

and this is what the system console says

```
bl_locale_set(): Conversion failed
Read prefs: C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend
bl_locale_set(): Conversion failed
found bundled python: C:\Program Files\Blender Foundation\Blender 2.90\2.90\python
register_class(...):
Warning: 'OBJECT_PT_custom_panel_' doesn't have an alpha-numeric suffix
register
Reloading external rigs...
Reloading external metarigs...
CAD Transform 0.0.8 : ready
Warning: class OBJECT_OT_mirror_all_vertexgroups contains a property which should be an annotation!
C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MirrorAllVertexGroups.py:230
    assign as a type annotation: OBJECT_OT_mirror_all_vertexgroups.action
    assign as a type annotation: OBJECT_OT_mirror_all_vertexgroups.enum_Axis
    assign as a type annotation: OBJECT_OT_mirror_all_vertexgroups.enum_Way
    assign as a type annotation: OBJECT_OT_mirror_all_vertexgroups.enum_Pattern
    assign as a type annotation: OBJECT_OT_mirror_all_vertexgroups.special_pattern
    assign as a type annotation: OBJECT_OT_mirror_all_vertexgroups.left_side
    assign as a type annotation: OBJECT_OT_mirror_all_vertexgroups.right_side
    assign as a type annotation: OBJECT_OT_mirror_all_vertexgroups.tolerance
addon_utils.disable: BlenderMalt not disabled
Modules Installed (BlenderMalt) from 'G:\\blendworks\\BLENDER ADDONS\\NOT IN USE YET\\malt\\BlenderMalt.zip' into 'C:\\Users\\Alan\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons'
Looking in links: c:\Users\Alan\AppData\Local\Temp\tmp6t7lod4x
Requirement already satisfied: setuptools in c:\program files\blender foundation\blender 2.90\2.90\python\lib\site-packages (41.2.0)
Requirement already satisfied: pip in c:\program files\blender foundation\blender 2.90\2.90\python\lib\site-packages (19.2.3)
Requirement already satisfied: PyOpenGL in c:\users\alan\appdata\roaming\python\python37\site-packages (3.1.5)
Requirement already satisfied: pcpp in c:\users\alan\appdata\roaming\python\python37\site-packages (1.21)
Requirement already satisfied: PyGLM in c:\users\alan\appdata\roaming\python\python37\site-packages (1.99.3)
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\__init__.py", line 31, in <module>
    import Malt
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\__init__.py", line 3, in <module>
    from Malt import GL
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\GL.py", line 5, in <module>
    import OpenGL
ModuleNotFoundError: No module named 'OpenGL'


```

**Comment by BlenderNPR** [comment]
Installed Blender will always fail to install BEER's dependencies.

**Solution:** try a **zip** version, then add a "**config**" folder inside of the 2.90 folder. 
Then install BEER/Malt like normal.
and please read the install guide thoroughly.

**Comment by pragma37** [comment]
Are you running Blender with a custom Python path?

It reports PyOpenGL and other dependencies as already installed, but on a Python path that it's not the one built in your Blender installation.

> Requirement already satisfied: setuptools in **c:\program files\blender foundation\blender 2.90\2.90\python\lib\site-packages** (41.2.0)

VS
>Requirement already satisfied: PyOpenGL in **c:\users\alan\appdata\roaming\python\python37\site-packages** (3.1.5)

If you go to the Console inside the Scripting workspace, paste `bpy.app.binary_path_python` then press ENTER, what does the console prints ?


@BlenderNPR 
> Installed Blender will always fail to install BEER's dependencies.

It should work as long as Blender has write permissions for its installation folder. Otherwise it's a bug.

**Comment by AnityEx** [comment]
So... I thought i fixed it by deleting the whole folder c:\users\alan\appdata\roaming\python\python37\site-packages (3.1.5) bc i was uninstalling python bc i dont use it so the file could download the dependencies where it should and it installed correctly

the file path you told me looks like this now
![image](https://user-images.githubusercontent.com/61922421/93380445-768dd200-f81c-11ea-9725-7d0a2306c6e1.png)

the problem now is, is that malt is not letting blender open at all when active

and if i open and then i activate it, it just crashes no matter what i do...


also yeah sorry heres my system info

[system-info.txt](https://github.com/BlenderNPR/BEER/files/5234318/system-info.txt)

now it downloaded everything fine and wont stop crashing I even reverted to default settings to see if it was something to do with my addons but no

**Comment by pragma37** [comment]
Yes, this is a different issue. Some people are having crashes since we started to use the GLM python library.
Sorry for that! I'm going to replace it ASAP.

**Comment by pragma37** [comment]
@AnityEx Could you try this version and tell me if it still crashes your Blender?

[BlenderMalt.zip](https://github.com/BlenderNPR/BEER/files/5241190/BlenderMalt.zip)

**Comment by pragma37** [comment]
Got confirmation from other users that the crashes are now fixed.

Closing this.
