### ISSUE TITLE
Material error when loading with Link

### ISSUE THREAD

**Issue by POPREQ** [BlenderNPR/BEER#102]
I have an error where the material is in its initial state when linking and need help.

1. Load the object with a link and use Override or Proxy to make the object or character editable.
2. Make a new save. The character's material will be the initial flat yellow color.
3.Depending on the model being loaded, Revert may not return the material to its initial state.

---

The error of the material turning yellow after a new save may occur even if no link is used.

I have a character whose material does not return after Revert, 
but due to confidentiality agreements, I cannot attach it here.

Instead, I'm attaching a simple Armature using Suzanne.
(Revert will reload the material here).
Can you please load this data in Link and see if the above error (up to 2) is reproduced?

The attached session log was obtained after Linking and Overriding the sample Armature in a new scene, and saving it anew.

[210728.zip](https://github.com/bnpr/Malt/files/6890202/210728.zip)

**Comment by pragma37** [comment]
Please, check the latest version.
I think it should be fixed now.

**Comment by POPREQ** [comment]
I checked!
Perfect. Thanks a lot.
