### ISSUE TITLE
Mesh Shader Missing

### ISSUE THREAD

**Issue by shuuee** [BlenderNPR/BEER#103]
Hello, this is possible a minor issue on my part but I'm not sure what to do. I recently download Malt for Blender 2.9.3 and installed it. I reloaded Blender and when I went to try out Malt, I noticed that the Mesh Shader wasn't there. I'm not sure if there's something else I need to install.

![malt](https://user-images.githubusercontent.com/88074040/127268078-6666f03e-5132-42b0-a20b-3121bb3908a7.PNG)

**Comment by pragma37** [comment]
Hi!
I need more info:
https://github.com/bnpr/Malt#bug-reports
