### ISSUE TITLE
Shader Compiler Error + Viewport being gray

### ISSUE THREAD

**Issue by Seus981** [BlenderNPR/BEER#108]
So,after enabling the add-on i wanted to try it,but the viewport remains gray despite the world having a changed color and any shader i try to add give me this error,
![image](https://user-images.githubusercontent.com/88315851/127834879-e3358557-911b-4973-9fa2-2e8df8f55051.png)

**Comment by BlenderNPR** [comment]
try this, [https://bnpr.gitbook.io/beer-malt-wiki/malt-gotchas#my-mesh-is-grey](https://bnpr.gitbook.io/beer-malt-wiki/malt-gotchas#my-mesh-is-grey) might be related

**Comment by Seus981** [comment]
I tried it before but it wouldn't solve anything for me sadly

**Comment by pragma37** [comment]
I need more info:
https://github.com/bnpr/Malt#bug-reports

**Comment by Seus981** [comment]
> I need more info:
> https://github.com/bnpr/Malt#bug-reports

After turning on the add-on and selecting malt as the rendering engine ,the Malt window opens but when i am going to the rendered view,neither the viewport or Malt window changes,and if i try loading any shader i get the error message shown in the image.Changing the background settings doesn't change the world setting as well.

**Comment by pragma37** [comment]
Please, read the link.

**Comment by Seus981** [comment]
I apologize,i did.Here are the log file and blender file put into a wetransfer link:
[malt 2021-08-03(20-11).log](https://github.com/bnpr/Malt/files/6925934/malt.2021-08-03.20-11.log)
https://we.tl/t-yYRcAt8xYI

**Comment by pragma37** [comment]
Could you try this version?
https://github.com/bnpr/Malt/releases/tag/debug-shader-compilation-latest

There have been other reports like this (#101), but only on Linux so far.

**Comment by Seus981** [comment]
It works now,thank you very much
