### ISSUE TITLE
Attempting to use AdvLine GLSL

### ISSUE THREAD

**Issue by paulhart2** [BlenderNPR/BEER#11]
**System Information**
Operating system: Windows-10-10.0.19041-SP0 64 Bits
Graphics card: GeForce RTX 2080 Ti/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 452.06

**Blender Version**
Broken: version: 2.90.0, branch: master, commit date: 2020-08-31 11:26, hash: `rB0330d1af29c0`
Worked: (newest version of Blender that worked as expected)

Errors while attempting to implement Advanced Line.glsl shader
_____________________________________________________________________
Error: PipelineTest : MAIN_PASS : SHADER COMPILER ERROR :
E:/BlenderRes/assets/Shader Examples/advanced_line.glsl(25) : error C0000: syntax error, unexpected $undefined at token "@"
E:/BlenderRes/assets/Shader Examples/advanced_line.glsl(28) : error C1503: undefined variable "get_specular"
E:/BlenderRes/assets/Shader Examples/advanced_line.glsl(29) : error C1503: undefined variable "diffuse"
E:/BlenderRes/assets/Shader Examples/advanced_line.glsl(31) : error C1503: undefined variable "get_line_advanced"
E:/BlenderRes/assets/Shader Examples/advanced_line.glsl(36) : error C0000: syntax error, unexpected reserved word "if" at token "if"
SHADER LINKER ERROR :
Fragment info
-------------
E:/BlenderRes/assets/Shader Examples/advanced_line.glsl(25) : error C0000: syntax error, unexpected $undefined at token "@"
E:/BlenderRes/assets/Shader Examples/advanced_line.glsl(28) : error C1503: undefined variable "get_specular"
E:/BlenderRes/assets/Shader Examples/advanced_line.glsl(29) : error C1503: undefined variable "diffuse"
E:/BlenderRes/assets/Shader Examples/advanced_line.glsl(31) : error C1503: undefined variable "get_line_advanced"
E:/BlenderRes/assets/Shader Examples/advanced_line.glsl(36) : error C0000: syntax error, unexpected reserved word "if" at token "if"
(0) : error C2003: incompatible options for link

Similar error while attempting to use Basic Line.glsl
_______________________________________________________________
Error: PipelineTest : MAIN_PASS : SHADER COMPILER ERROR :
E:/BlenderRes/assets/Shader Examples/basic_line.glsl(13) : error C0000: syntax error, unexpected $undefined at token "@"
E:/BlenderRes/assets/Shader Examples/basic_line.glsl(16) : error C1503: undefined variable "get_specular"
E:/BlenderRes/assets/Shader Examples/basic_line.glsl(17) : error C1503: undefined variable "diffuse"
E:/BlenderRes/assets/Shader Examples/basic_line.glsl(19) : error C1503: undefined variable "get_line_simple"
E:/BlenderRes/assets/Shader Examples/basic_line.glsl(21) : error C0000: syntax error, unexpected '=', expecting "::" at token "="
SHADER LINKER ERROR :
Fragment info
-------------
E:/BlenderRes/assets/Shader Examples/basic_line.glsl(13) : error C0000: syntax error, unexpected $undefined at token "@"
E:/BlenderRes/assets/Shader Examples/basic_line.glsl(16) : error C1503: undefined variable "get_specular"
E:/BlenderRes/assets/Shader Examples/basic_line.glsl(17) : error C1503: undefined variable "diffuse"
E:/BlenderRes/assets/Shader Examples/basic_line.glsl(19) : error C1503: undefined variable "get_line_simple"
E:/BlenderRes/assets/Shader Examples/basic_line.glsl(21) : error C0000: syntax error, unexpected '=', expecting "::" at token "="
(0) : error C2003: incompatible options for link

**Comment by pragma37** [comment]
Are you sure you're not using a very old addon version?

Could you try the latests?
https://github.com/BlenderNPR/BEER/suites/1214601550/artifacts/18104455

**Comment by paulhart2** [comment]
Thank you, I did not receive the same errors, using the Source you 
indicated.
Some of clarity and direction would be helpful, regarding downloading 
'both' BEER and BlenderMalt, current versions.
I have no idea what settings are needed to actually get the line 
rendering that seems to be intended.
Is this something that can be set for a Collection??, or does it need be 
done for each object??
I tried it both ways?? and nothing shows up, using Malt as the Render 
Engine?
As a BNPR contributing member, I find myself confounded.
I appreciate your working on this crucial project, looking forward to 
actual output on my station.

I am including a Screen Shot of the single object I intend to render. 
Crow...

Signature HARTWORKS
Paul Hartsuyker
HARTWORKS <http://www.hartworks.net>
paul@hartworks.net <mailto:paul@hartworks.net>
619-269-8939

**Comment by BlenderNPR** [comment]
Hi Paul,

All the installation instructions are here.
https://github.com/BlenderNPR/BEER/blob/master/BlenderMalt/readme.md

Malt is the backend of BEER so it is not as user friendly as BEER ultimately would be.
All the friendly UI will be done in the front end part of the project.
Which is after Malt is done.

Right now everything is a shader.
1 material per object, also means 1 glsl shader per material per object.
There is no separation between line art and other shaders.
Malt has no idea of collection yet.

So to answer your question:
to get line art, create a material, add the line art shader (.glsl), change to rendered preview
if everything is super dark, change lamp to sun lamp and you will see the shading with the line art.

Alternatively, hit us up on Discord so that we can help you solve any difficulties.
https://discord.gg/9qeVxQQ

-- Light BWK

**Comment by paulhart2** [comment]
Thank you for the response. I will try again with a more recent version to see if it is more user 'friendly.'
