### ISSUE TITLE
Cannot enable BlenderMalt

### ISSUE THREAD

**Issue by Cristosan** [BlenderNPR/BEER#12]
The addon is installed with no problem, but when I try to enable it, an error message appears and it cannot be enabled.

SCREENSHOT
![Screenshot_2](https://user-images.githubusercontent.com/62618457/94597300-b083bd00-028d-11eb-8835-74b0008d28a8.jpg)

SYSTEM INFO
[system-info.txt](https://github.com/BlenderNPR/BEER/files/5300952/system-info.txt)

SYSTEM COSOLE CONTENTS
Read prefs: C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.90\2.90\python
_______REgister previews
.. .ao
.. .ao_legacy
.. .bevel_mask
.. .cavity
.. .curvature
.. .diffuse
.. .displacment
.. .dust
.. .id_element
.. .id_material
.. .normal_object
.. .normal_object_bevel
.. .normal_tangent
.. .normal_tangent_bevel
.. .paint_base
.. .position
.. .selection
.. .wireframe
Looking in links: c:\Users\pc\AppData\Local\Temp\tmpa6y9c8rd
Requirement already satisfied: setuptools in c:\program files\blender foundation\blender 2.90\2.90\python\lib\site-packages (41.2.0)
Requirement already satisfied: pip in c:\program files\blender foundation\blender 2.90\2.90\python\lib\site-packages (19.2.3)
Collecting PyOpenGL
  Using cached https://files.pythonhosted.org/packages/47/9a/8d9364533ebcaa13621994a63dcc6a6051e27671ae5e1715dac4af18cac2/PyOpenGL-3.1.5-py3-none-any.whl
Installing collected packages: PyOpenGL
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Accesso negato: 'C:\\Program Files\\Blender Foundation\\Blender 2.90\\2.90\\python\\Lib\\site-packages\\OpenGL'
Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 19.2.3, however version 20.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\__init__.py", line 15, in <module>
    import OpenGL, pcpp, pyrr
ModuleNotFoundError: No module named 'OpenGL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\pc\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\__init__.py", line 22, in <module>
    subprocess.check_call([bpy.app.binary_path_python, '-m', 'pip', 'install', dependency])
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Blender Foundation\\Blender 2.90\\2.90\\python\\bin\\python.EXE', '-m', 'pip', 'install', 'PyOpenGL']' returned non-zero exit status 1.

BLEND FILE
[BEER bug.zip](https://github.com/BlenderNPR/BEER/files/5300974/BEER.bug.zip)

GO TO ADDONS>RENDER>ENABLE BLENDERMALT

**Comment by pragma37** [comment]
For a correct installation you have to run Blender with administrator privileges, unless you use a portable (ZIP version) of Blender.

From your system console message:

```
Installing collected packages: PyOpenGL
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Accesso negato: 'C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\Lib\site-packages\OpenGL'
Consider using the --user option or check the permissions.
```

**Comment by HellHound0** [comment]
![image](https://user-images.githubusercontent.com/72498461/95324610-49bf5e80-08a0-11eb-97cf-3c1c315ad60c.png)
![image](https://user-images.githubusercontent.com/72498461/95324698-6cea0e00-08a0-11eb-8c52-bc9c8547d9f0.png)

Hi I'm having a similar error I can't install it in either zipped blender or not. I tried a few different versions including the newest version of Blender. How do I fix it please? I tried enabling Full permissions in the security folders everywhere Blender is installed but nothing worked.

**Comment by pragma37** [comment]
@HellHound0 
From your first error. I'm not sure, but it looks like you were running Blender from a temp folder? Please extract Blender first to a regular folder (like your desktop).
I think the second one should be fixed now, so please download the latest BlenderMalt version before trying to install it again.

**Comment by HellHound0** [comment]
Hi @pragma37 
Thanks. I ran the new version on the desktop and it worked!

**Comment by pragma37** [comment]
@HellHound0 
Great! 

I'm closing the issue since the original author never responded.
