### ISSUE TITLE
won't render

### ISSUE THREAD

**Issue by UselessBay** [BlenderNPR/BEER#136]
the scenes look good in the viewport but images won't render and videos render only the first frame

**Comment by pragma37** [comment]
Logs?
https://github.com/bnpr/Malt#bug-reports

**Comment by UselessBay** [comment]
Hello Miguel
No log because I don't know if it's a bug or just some setting I haven't gotten on Blender
Perhaps this isn't the right forum for my issue but I haven't been able to find any troubleshooting elsewhere about this problem.

Useless Bay


________________________________
