### ISSUE TITLE
IS there a MacOS version?

### ISSUE THREAD

**Issue by winniejo** [BlenderNPR/BEER#14]
IS there a MacOS test version?

**Comment by pragma37** [comment]
Hi!
The addon works on MacOS, but it must be installed manually for now.

https://github.com/BlenderNPR/BEER/tree/master/BlenderMalt#manual-installation

**Comment by winniejo** [comment]
Terima kasih , Thank you very much for the work its a good idea.

Jo

**Comment by pragma37** [comment]
Now all OS versions are distributed the same way, so I'm closing this.
