### ISSUE TITLE
Extra lines on faces using a vertex shader

### ISSUE THREAD

**Issue by clacker** [BlenderNPR/BEER#15]
I made what I felt was a simple vertex shader.  It moves the POSITION.xy of a vertex based on the POSITION z value.  It worked fine until I added lines to the pixel shader and then I got some artifacts on the faces.  The artifacts follow the color of the lines and are affected by the line width.  I tried scaling the normals as well but it didn't help.  The artifacts move as I rotate the viewport around.
[vertex material and lines issue.zip](https://github.com/BlenderNPR/BEER/files/5469838/vertex.material.and.lines.issue.zip)

**Comment by pragma37** [comment]
This is because you are modifying the vertex positions but not its normals.

For freely modifying the vertex positions and getting the new normals calculated automatically for you, use the VERTEX_DISPLACEMENT macro.


```glsl
uniform vec3 ambient_color = vec3(0.1,0.1,0.1);
uniform vec3 diffuse_color = vec3(1.0,0.1,0.1);
uniform vec3 specular_color = vec3(1.0,1.0,1.0);
uniform float roughness = 0.5;

uniform vec3 line_color = vec3(0.0,0.0,0.0);
uniform float line_width = 1.0;
uniform float line_depth_threshold = 0.5;
uniform float line_normal_threshold = 1.0;

vec3 displace(vec3 position)
{
    position.xy *= position.z + 2.0;
    return position;
}

@COMMON_VERTEX_SHADER
{
    DEFAULT_VERTEX_SHADER();

    VERTEX_DISPLACEMENT(displace, 0.01);

    VERTEX_SETUP_OUTPUT();
}

@MAIN_PASS_PIXEL_SHADER
{
    vec3 diffuse = diffuse_color * get_diffuse();
    vec3 specular = specular_color * get_specular(roughness);
    vec3 color = ambient_color + diffuse + specular;

    float line = get_line_simple(line_width, line_depth_threshold, line_normal_threshold);

    color = mix(color, line_color, line);

    OUT_COLOR = vec4(color, 1.0);
}
```

**Comment by clacker** [comment]
Thank you for looking into it.  I checked your code and you are correct, using that macro fixed it.
