### ISSUE TITLE
Texture Samplers Cause Object To Not Render

### ISSUE THREAD

**Issue by PointDevice** [BlenderNPR/BEER#150]
I started with the node tree system, and ran into an issue where an object would blank out when using a texture sampler
![NodeTreeError](https://user-images.githubusercontent.com/88350084/137911561-f5f1d1f8-5c48-4566-b626-158696d4a86e.PNG)
For sanity check, i set the color to a static value and it works fine as expected
![NodeTreeExpected](https://user-images.githubusercontent.com/88350084/137911567-0da9e0e5-ba59-4772-b102-4549013b3bb9.PNG)
Then using the basic_texture.mesh.glsl sahder a similar error occurs, this time it looks as if then entire scene is treated as transparent
![ShaderMeshFileError](https://user-images.githubusercontent.com/88350084/137911571-ec3cb7fd-db12-4a6f-ae07-cced74c9bbdf.PNG)
Sanity checking with the basic.mesh.glsl shader to ensure that everything in the project was fine and it gives and expected result
![ShaderMeshFileExpected](https://user-images.githubusercontent.com/88350084/137911576-0aa27c60-0b33-4750-a9e8-0240634f5272.PNG)

using blender 2.82.7 and the latest at the time release from commit  6ed92fb
if you need any further information please let me know

**Comment by pragma37** [comment]
Hi!
In your first image, you are using the UV at index 1.
Assuming that's the default cube, it only has one UV at index 0.

Your second image looks like an actual bug. I can't know what could have caused it without the [log files](https://github.com/bnpr/Malt#bug-reports).
That said, Blender 2.82 is actually older than Malt itself, it may simply be incompatible.
I would start by upgrading to 2.93 (at least for Malt).

**Comment by PointDevice** [comment]
HI, thank you for the quick feed back, i did try with different UV indexes, and they all gave the same result, i forgot to set it to 0 when taking the screen shot for the issue, i will try with a newer version of blender and see if that was the cause, if it persists ill grab a log file, thank you again!
