### ISSUE TITLE
Material options dont appear.

### ISSUE THREAD

**Issue by ca3games** [BlenderNPR/BEER#152]
Blender 2.93
Kubuntu 21.10
AMD Vega 8 with Ryzen 3200 G

Imported malt and basic shader material.
Options dont appear and render comes as full transparency, object isnt rendered.
![Screenshot_20211030_151312](https://user-images.githubusercontent.com/19626687/139557315-00abbbcc-efba-4d73-a130-83869ed86085.png)
![Screenshot_20211030_151312](https://user-images.githubusercontent.com/19626687/139557389-bcfa2223-01a5-4157-9291-7e60e933928a.png)

**Comment by pragma37** [comment]
I need more info.
https://github.com/bnpr/Malt#bug-reports

**Comment by ca3games** [comment]
@pragma37 
[malt 2021-11-03(12-18).log](https://github.com/bnpr/Malt/files/7469520/malt.2021-11-03.12-18.log)

**Comment by pragma37** [comment]
It should be fixed in the latest version. 👍
