### ISSUE TITLE
Addon Blender BEER/Malt not being istalled 

### ISSUE THREAD

**Issue by MicroDraw** [BlenderNPR/BEER#154]
from that link https://www.youtube.com/watch?v=tnXnmcC49iU&t=1s

i followed the instructions and the addon is not being able to be installed.

on blender window Preferences and the tag Add ons it does not show up the name to check it on checkbox.

**Comment by pragma37** [comment]
Try to install it the normal way:
https://github.com/bnpr/Malt/#install

If that doesn't work, copy-paste the System Console content here so we can take a look.
