### ISSUE TITLE
Object renders gray, little windows pop up and disappear, AttributeError every second in console

### ISSUE THREAD

**Issue by LordMcMutton** [BlenderNPR/BEER#162]
Using Blender 2.92 and the latest release of Malt at the date of posting

When using Malt as the render engine, rendered objects show up as gray or transparent?

![image](https://user-images.githubusercontent.com/93609836/141168276-8bc4eab5-86d3-4901-8a0f-e821a3b8a707.png)

The Console logs the following error every second:

![image](https://user-images.githubusercontent.com/93609836/141168385-18f7f184-cbd7-42de-bcb5-4522ab9b92a5.png)

And every time an action is performed in the viewport, a small popup appears, minimizes, and then closes- this is the same issue shown in the video on Issue #144 

And here's the Session Log:
[malt 2021-11-10(11-55).log](https://github.com/bnpr/Malt/files/7514983/malt.2021-11-10.11-55.log)

**Comment by pragma37** [comment]
Looks like GLSLParser (one of the executables that Malt uses internally) fails with exit code 3221225785.

Seems like your installed C++ runtime libraries are too old.
You can try to install the latest version:
https://aka.ms/vs/16/release/vc_redist.x64.exe
But maybe even the latest C++ runtime supported by Windows 7 is not enough, I have no idea.

**Comment by LordMcMutton** [comment]
They don't seem to be enough, no- the issue persists.

So if the latest versions of Malt are intended to be used with the latest versions of Blender, it looks like the 2.92>2.93 divide is where it stops working for Windows 7.

**Comment by pragma37** [comment]
Sorry, but Windows 7 support has been discontinued by Microsoft for almost 2 years.
There's probably a way to work around the issue, but I'm already spread too thin and I have to prioritize.

Unless it is impossible for you for some reason, I would recommend upgrading to Windows 10.
