### ISSUE TITLE
Weird error if laptop is not attached to power source (running on battery)

### ISSUE THREAD

**Issue by JPLost** [BlenderNPR/BEER#167]
![kuva](https://user-images.githubusercontent.com/48565494/141836428-b6876b6d-8702-4342-9f81-559a9242e888.png)

This happens if I run Blender on battery.

Asus FX505G

**Comment by pragma37** [comment]
I guess your laptop uses the integrated card when on battery-saving mode.

For some reason, PyOpenGL doesn't support the texture data format that your GPU reports as optimal.
I added a fallback to a sane default when the optimal format fails. (7582ab8d157bf094734d9e665dca9309d9bc2d4b)
The latest release should work fine.
