### ISSUE TITLE
Startup file : Malt shaders can't be found.

### ISSUE THREAD

**Issue by Arkadeievitch** [BlenderNPR/BEER#17]
Hello,
I tried to save a file using Malt shaders as startup file. For some reason, the shaders path seem to be lost by default.

To reproduce it :
1/ Create a model using Malt as renderer. It should contain a mesh with a malt material. Load the shader you want in the material malt settings.
2/ Save the file normally (for reference).
3/ Save the file as startup file (File>Defaults>Save Startup File).

4/ Close and open Blender. Skip the startup menu. Your file should be loaded by default. Although its material should appear yellow. If you select the shader again, it appears.
If you open the same file by loading it normally, it should work directly.

Blender version : 2.90.0
OS : Windows10

**Comment by pragma37** [comment]
Hi! Thanks for the report.

You probably saved the path to the shader as Relative, therefore if you don't open the blend file from the same location it can't find it. You will have the same issue if you just save the file to a different folder.

Blender automatically remaps relative paths for built-in properties but for some reason it doesn't do the same for custom properties.

This should be handled more gracefully, ideally by submitting a patch to Blender to handle custom path properties too. But for now just uncheck the Relative Path option in the File Browser dialog when you select a shader file.
https://docs.blender.org/manual/en/latest/editors/file_browser.html?highlight=relative%20path#operator-panel

**Comment by Arkadeievitch** [comment]
OK, this seems to work perfectly.
Thanks a lot!
