### ISSUE TITLE
No rendering output

### ISSUE THREAD

**Issue by Arkadeievitch** [BlenderNPR/BEER#18]
Hello,
Tried to test some rendering with Malt, but I dont get anything at the output.
I tried to tick different boxes in this menu without result :
![image](https://user-images.githubusercontent.com/49653750/99184976-26ad8780-2747-11eb-8515-64f104c84615.png)

My model is a test of all the Malt shaders (here, the render preview in 3D viewport) : 
![image](https://user-images.githubusercontent.com/49653750/99185081-cc60f680-2747-11eb-8ae1-9cb64a3a141a.png)

My output shows an empty picture (fully transparent).
I use CUDA for display, which works fine. Eevee and Cycles both seem to work too.

Tell me if you need my file to test it.

Maybe there is something that I missed. I didn't find detailed tutorial about blender setup for Malt.

Blender version : 2.90.0
OS : Windows10

System:
CPU: AMD Ryzen5 1600
GPU: GeForce GTX960

**Comment by Arkadeievitch** [comment]
OK, I just had to run it as administrator.
I know that I read it somewhere in Malt documentation, but I'm unable to find where again.

**Comment by pragma37** [comment]
Hi, thanks for your report.

This was broken by a recent optimization change, should be easy to fix.

Running Blender as admin when installing Malt shouldn't be needed anymore and I doubt it's related to this problem.

If you open Blender and render your file before switching to the viewport render mode then the first render will work. But then subsequent renders and the viewport won't work. That's probably what happened.

Could you check if that's the case?

**Comment by Arkadeievitch** [comment]
Well, sorry, but I stepped in another problem doing the following tests.

My startup file had its viewport shading set to "material preview": 
![image](https://user-images.githubusercontent.com/49653750/99197397-92691200-2792-11eb-963d-8d989d0fc22d.png)
- Whenever I try to set it back to Wireframe or Solid, Blender crashes. Same if I try to change the render engine.
However, I can switch between Material Preview and Rendered.
- If I don't touch anything and try to render, I only get an empty frame.
- If I disable/enable again Malt, I can switch again my viewport, but rendering produces an empty frame.
- If I restart Blender after the previous steps, I get the behaviour you just described: good rendering before touching anything, then empty frame after switching viewport mode.


Here is what I get in Info tab when I try to render :

```
Traceback (most recent call last):
  File "C:\Users\CaptainSweet\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltRenderEngine.py", line 194, in render
    render_textures = self.get_pipeline().render(resolution, scene, True, False)
  File "C:\Users\CaptainSweet\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\Pipeline.py", line 219, in render
    self.result = self.do_render(resolution, scene, is_final_render, is_new_frame)
  File "C:\Users\CaptainSweet\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\PipelineTest.py", line 111, in do_render
    scene.parameters['ShadowMaps Point Resolution'])
  File "C:\Users\CaptainSweet\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\Render\Lighting.py", line 230, in load
    fbo.clear(depth=1)
  File "C:\Users\CaptainSweet\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\RenderTarget.py", line 69, in clear
    self.bind()
  File "C:\Users\CaptainSweet\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\RenderTarget.py", line 64, in bind
    glBindFramebuffer(GL_FRAMEBUFFER, self.FBO[0])
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glBindFramebuffer,
	cArguments = (GL_FRAMEBUFFER, 24)
)

location: <unknown location>:-1
```

There are then two problems : 
- The empty rendering, which occurs the most.
- The crashes, which occur in yet undefined cases, but can be reproduced systematically on "corrupted" files.

I'll continue doing tests to see if I can understand better in which conditions each of them appear. Don't hesitate to tell me if you need specific ones. 
If needed, do you have a prefered way to share files?

**Comment by pragma37** [comment]
Do not apologize, I'm thankful for the reports.

If you have a file that crashes reliably that would be really handy.
If you don't mind sharing it publicly you can upload it here directly by attaching it to your replay. Otherwise you can mail it to me to pragma37@gmail.com.

**Comment by Arkadeievitch** [comment]
Well, I see some crashes, but the hell if I understand how to reproduce them...
This file seemed to crash when I tried to change tab, but it also resolved by unticking/ticking again Malt in preferences : 
[test_Startup_Malt.zip](https://github.com/BlenderNPR/BEER/files/5547433/test_Startup_Malt.zip)

F12 works fine now, thank you!
I guess that I can close this issue and open a new one if I find more about crashes. Is that OK for you?

**Comment by pragma37** [comment]
It's not crashing on my computer.

Could you try with Blender 2.91 and tell me if it also crashes there? (See #16 for reference)

Then we can close this issue.
