### ISSUE TITLE
Node links made from custom 'x_from_y' shader functions disconnect on startup

### ISSUE THREAD

**Issue by Kolupsy** [BlenderNPR/BEER#186]
I made some functions defining type conversions in a glsl script thats used on most of the shader trees in a project. When I reopen the file all those links get disconnected and I need to manually reconnect the sockets. Its not that the connection is invalid but it seems that the links are being evaluated before the custom script is being considered.
This is the code:
`float float_from_vec4( vec4 col ){
    return col.r;
}`
`float float_from_vec3( vec3 col ){
    return col.r;
}`
`float float_from_bool( bool b ){
    return float( b );
}`
Im loading the script through the NodeTree.library_source property

**Comment by pragma37** [comment]
I just tested this myself and seems to work fine.

More info?
https://github.com/bnpr/Malt#bug-reports

**Comment by Kolupsy** [comment]
I cannot seem to replicate the error, works fine now. I would have made more tests but I was too scared to close the file and reopen because it took a long time to reconnect these sockets. I hope it doesnt happen again. But if it does, i will try to find out what caused it
