### ISSUE TITLE
 realtime rendering does not work with Malt in blender 2.93. can you help me?

### ISSUE THREAD

**Issue by DeeperMoran** [BlenderNPR/BEER#189]
https://user-images.githubusercontent.com/67450193/144726573-176ea83a-0036-40f3-a705-3f720a003e6c.mp4

help me!

**Comment by lamartuffy** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/71610144/144758988-6ae219e7-bf81-444e-afb1-88fcb6ea283e.png)
 i can add more screenshots, rendering mode isn't working, but i can rotate scene and i can see results of rotation, but image on screen doesn't change

**Comment by pragma37** [comment]
https://github.com/bnpr/Malt#bug-reports
