### ISSUE TITLE
[Blender 2.91] NPR_Pipeline : PRE_PASS : SHADER COMPILER ERROR

### ISSUE THREAD

**Issue by Arkadeievitch** [BlenderNPR/BEER#20]
Hello,

I'm having the following error that appears when I select a shader :
![Screen_BugMaltShader](https://user-images.githubusercontent.com/49653750/101262233-5dbafb80-373d-11eb-9936-55280624cac4.png)

I uninstalled the previous Malt release and installed the new one, then I got this error (either when I select a shader in a new material slot or in former one).

Is there something to do when installing/uninstalling to avoid this? 
Maybe it has nothing to do with this, but I noticed that there was a slot for ""Malt library path" in preferences/Add-ons/Renderer: Malt. I tried a few (empty, shaders path and Malt path), but none of them seemed to have any effect.

**Comment by pragma37** [comment]
Update your shader examples too.
I added new functionality that broke backwards compatibility for shaders.

**Comment by Arkadeievitch** [comment]
Ah ok, you're right. Thank you!
