### ISSUE TITLE
Malt poor perfomance, AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

### ISSUE THREAD

**Issue by f1ow03** [BlenderNPR/BEER#209]
Tried MALT (latest stable) on both Blender 2.93.6 and Blender 3.0. Blender becomes unusable, it lags, constantly processing something in the background and continuously reports same error:

> 
> File "/home/user/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 169, in track_shader_changes
>     compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()
> AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'
> Traceback (most recent call last):
>   File "/home/user/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 169, in track_shader_changes
>     compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()
> AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Im using MESA driver ver 21.2.6 if that might help somehow.

**Comment by pragma37** [comment]
Logs?
https://github.com/bnpr/Malt#bug-reports

**Comment by f1ow03** [comment]
[malt log.log](https://github.com/bnpr/Malt/files/7770479/malt.log.log)

**Comment by pragma37** [comment]
So it's not just bad performance, it doesn't work at all, right?
What Linux distribution is this?

Seems like the issue is in the GLSLParser, but the error code is not useful at all.
If you run `"/home/user/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/GL/GLSLParser/.bin/GLSLParser" "/home/user/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/Shaders/Common/Transform.glsl"` in the command line, what does it print?

**Comment by f1ow03** [comment]
I'm on Xubuntu 18.04

> /home/user/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/GL/GLSLParser/.bin/GLSLParser: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by /home/user/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/GL/GLSLParser/.bin/GLSLParser)`

**Comment by pragma37** [comment]
The standard C++ libraries in your OS are older than the one used by Github Actions for compiling the addon.

I updated the build instructions to run on Ubuntu 18.04 (the oldest version available in Github Actions).
Hopefully, that will solve the issue. 

If it doesn't you will have to upgrade your libstdc++ package.
