### ISSUE TITLE
Conflict the shape key autokeyframe

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#218]
### Malt version

Development-latest

### Blender version

Blender 3.00

### OS

Windows 10 64bits

### Hardware info

Intel i5-9400F | 8 GB RAM | NVDIA GTX 1660 Ti

### Issue description and reproduction steps

step1, enable malt in the render engine
step2, click the cube
step3, drag the frame to 100
step4, change the shape key value

### Attachments

[conflict.with.shape.key.zip](https://github.com/bnpr/Malt/files/7805299/conflict.with.shape.key.zip)

https://user-images.githubusercontent.com/36077492/148009217-1fdb9c20-5475-4233-a155-2fda9f9fdc67.mp4

[malt 2022-01-04(12-20).log](https://github.com/bnpr/Malt/files/7805310/malt.2022-01-04.12-20.log)

**Comment by pragma37** [comment]
I still can't reproduce it. 
I can set keyframes and animate it without any issues.
I'm using the same OS, Blender version and even CPU and GPU brand.

Does it only happen with autokeyframe?
Could you upload the [Blender Crash Log](https://docs.blender.org/manual/en/latest/troubleshooting/crash.html#crash-log) too?

**Comment by HSDSZ** [comment]
[conflict with shape key.crash.txt](https://github.com/bnpr/Malt/files/7811894/conflict.with.shape.key.crash.txt)

Here is the crash log. I can also reproduce the crash without autokeyframe.

**Comment by pragma37** [comment]
I checked it again on a diferent computer with a clean Blender installation and I still can't reproduce it.
And the crash log doesn't seem to have any relation with Malt.

Can you reproduce the issue on a clean Blender installation with default settings and only Malt installed?

**Comment by HSDSZ** [comment]
I chekck

**Comment by HSDSZ** [comment]
Sorry for the late reply. I checked the crash by disabling my addon one by one. I found crashes happens when "wiggle bone" addon is enabled while the render engine is set to MALT.

Wiggle bone disabled, MALT engine enable, No crash
Wiggle bone enabled, EEVEE engine enable, No crash
Wiggle bone enabled, MALT engine enable, crash

**Comment by HSDSZ** [comment]
This is not an urgent issue because wiggle bone is not widely used. I can just disable wiggle bone then MALT works fine
