### ISSUE TITLE
Utils not executable on Linux

### ISSUE THREAD

**Issue by Joeboy** [BlenderNPR/BEER#232]
### Malt version

1.0 Preview

### Blender version

Blender 3.0.1

### OS

Ubuntu Linux 21.10

### Hardware info

Intel i7-9750H | 16GB RAM | Nvidia Quadro T2000

### Issue description and reproduction steps

Hi! I'm excited for malt3d but seeing some issues getting it working. First issue I see is that after installing, it seems like some things ought to be executable but aren't, including (but maybe not limited to) GLSLParser and mcpp-Linux

### Attachments

I'm ignoring the instructions and copying and pasting because drag and drop doesn't work for me (using nautilus / gnome)

`Blender > SETUP IOCapture
Malt > DEBUG MODE: False
Malt > CONNECTIONS:
Malt > Name: MAIN Adress: ('127.0.0.1', 42325)
Malt > Name: REFLECTION Adress: ('127.0.0.1', 34841)
Malt > SYSTEM INFO
Malt > --------------------------------------------------------------------------------
Malt > PYTHON: 3.9.7 (default, Oct 11 2021, 10:06:01) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
Malt > OS: Linux-5.13.0-28-generic-x86_64-with-glibc2.34
Malt > CPU: x86_64
Malt > OPENGL CONTEXT:
Malt > NVIDIA Corporation
Malt > Quadro T2000/PCIe/SSE2
Malt > 4.1.0 NVIDIA 470.86
Malt > 4.10 NVIDIA via Cg compiler
Malt > GL_ARB_bindless_texture support : True
Malt > GL_MAX_3D_TEXTURE_SIZE: 16384
Malt > GL_MAX_ARRAY_TEXTURE_LAYERS: 2048
Malt > GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS: 8
Malt > GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE: 65536
Malt > GL_MAX_CLIP_DISTANCES: 8
Malt > GL_MAX_CLIP_PLANES: 8
Malt > GL_MAX_COLOR_ATTACHMENTS: 8
Malt > GL_MAX_COLOR_TEXTURE_SAMPLES: 64
Malt > GL_MAX_COMBINED_ATOMIC_COUNTERS: 98304
Malt > GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS: 48
Malt > GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES: 8
Malt > GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS: 231424
Malt > GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS: 233472
Malt > GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS: 231424
Malt > GL_MAX_COMBINED_IMAGE_UNIFORMS: 48
Malt > GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS: 16
Malt > GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES: 16
Malt > GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS: 96
Malt > GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS: 231424
Malt > GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS: 231424
Malt > GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: 192
Malt > GL_MAX_COMBINED_UNIFORM_BLOCKS: 84
Malt > GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS: 233472
Malt > GL_MAX_COMPUTE_ATOMIC_COUNTERS: 16384
Malt > GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS: 8
Malt > GL_MAX_COMPUTE_IMAGE_UNIFORMS: 8
Malt > GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS: 16
Malt > GL_MAX_COMPUTE_SHARED_MEMORY_SIZE: 49152
Malt > GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS: 32
Malt > GL_MAX_COMPUTE_UNIFORM_BLOCKS: 14
Malt > GL_MAX_COMPUTE_UNIFORM_COMPONENTS: 2048
Malt > GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS: 1024
Malt > GL_MAX_CUBE_MAP_TEXTURE_SIZE: 32768
Malt > GL_MAX_CULL_DISTANCES: 8
Malt > GL_MAX_DEBUG_GROUP_STACK_DEPTH: 64
Malt > GL_MAX_DEBUG_GROUP_STACK_DEPTH_KHR: 64
Malt > GL_MAX_DEBUG_LOGGED_MESSAGES: 128
Malt > GL_MAX_DEBUG_LOGGED_MESSAGES_KHR: 128
Malt > GL_MAX_DEBUG_MESSAGE_LENGTH: 1024
Malt > GL_MAX_DEBUG_MESSAGE_LENGTH_KHR: 1024
Malt > GL_MAX_DEPTH_TEXTURE_SAMPLES: 64
Malt > GL_MAX_DRAW_BUFFERS: 8
Malt > GL_MAX_DUAL_SOURCE_DRAW_BUFFERS: 1
Malt > GL_MAX_ELEMENTS_INDICES: 1048576
Malt > GL_MAX_ELEMENTS_VERTICES: 1048576
Malt > GL_MAX_ELEMENT_INDEX: -1
Malt > GL_MAX_EVAL_ORDER: 8
Malt > GL_MAX_FRAGMENT_ATOMIC_COUNTERS: 16384
Malt > GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS: 8
Malt > GL_MAX_FRAGMENT_IMAGE_UNIFORMS: 8
Malt > GL_MAX_FRAGMENT_INPUT_COMPONENTS: 128
Malt > GL_MAX_FRAGMENT_INTERPOLATION_OFFSET: 1
Malt > GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS: 16
Malt > GL_MAX_FRAGMENT_UNIFORM_BLOCKS: 14
Malt > GL_MAX_FRAGMENT_UNIFORM_COMPONENTS: 4096
Malt > GL_MAX_FRAGMENT_UNIFORM_VECTORS: 1024
Malt > GL_MAX_FRAMEBUFFER_HEIGHT: 32768
Malt > GL_MAX_FRAMEBUFFER_LAYERS: 2048
Malt > GL_MAX_FRAMEBUFFER_SAMPLES: 64
Malt > GL_MAX_FRAMEBUFFER_WIDTH: 32768
Malt > GL_MAX_GEOMETRY_ATOMIC_COUNTERS: 16384
Malt > GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS: 8
Malt > GL_MAX_GEOMETRY_IMAGE_UNIFORMS: 8
Malt > GL_MAX_GEOMETRY_INPUT_COMPONENTS: 128
Malt > GL_MAX_GEOMETRY_OUTPUT_COMPONENTS: 128
Malt > GL_MAX_GEOMETRY_OUTPUT_VERTICES: 1024
Malt > GL_MAX_GEOMETRY_SHADER_INVOCATIONS: 32
Malt > GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS: 16
Malt > GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS: 32
Malt > GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS: 1024
Malt > GL_MAX_GEOMETRY_UNIFORM_BLOCKS: 14
Malt > GL_MAX_GEOMETRY_UNIFORM_COMPONENTS: 2048
Malt > GL_MAX_IMAGE_SAMPLES: 64
Malt > GL_MAX_IMAGE_UNITS: 8
Malt > GL_MAX_INTEGER_SAMPLES: 64
Malt > GL_MAX_LABEL_LENGTH: 256
Malt > GL_MAX_LABEL_LENGTH_KHR: 256
Malt > GL_MAX_LIGHTS: 8
Malt > GL_MAX_LIST_NESTING: 64
Malt > GL_MAX_MODELVIEW_STACK_DEPTH: 32
Malt > GL_MAX_NAME_STACK_DEPTH: 128
Malt > GL_MAX_PATCH_VERTICES: 32
Malt > GL_MAX_PIXEL_MAP_TABLE: 65536
Malt > GL_MAX_PROGRAM_TEXEL_OFFSET: 7
Malt > GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET: 31
Malt > GL_MAX_PROJECTION_STACK_DEPTH: 4
Malt > GL_MAX_RECTANGLE_TEXTURE_SIZE: 32768
Malt > GL_MAX_RENDERBUFFER_SIZE: 32768
Malt > GL_MAX_SAMPLES: 64
Malt > GL_MAX_SAMPLE_MASK_WORDS: 2
Malt > GL_MAX_SERVER_WAIT_TIMEOUT: -1
Malt > GL_MAX_SHADER_STORAGE_BLOCK_SIZE: 2147483647
Malt > GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS: 96
Malt > GL_MAX_SUBROUTINES: 1024
Malt > GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS: 1024
Malt > GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS: 16384
Malt > GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS: 8
Malt > GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS: 8
Malt > GL_MAX_TESS_CONTROL_INPUT_COMPONENTS: 128
Malt > GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS: 128
Malt > GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS: 16
Malt > GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS: 32
Malt > GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS: 4216
Malt > GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS: 14
Malt > GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS: 2048
Malt > GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS: 16384
Malt > GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS: 8
Malt > GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS: 8
Malt > GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS: 128
Malt > GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS: 128
Malt > GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS: 16
Malt > GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS: 32
Malt > GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS: 14
Malt > GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS: 2048
Malt > GL_MAX_TESS_GEN_LEVEL: 64
Malt > GL_MAX_TESS_PATCH_COMPONENTS: 120
Malt > GL_MAX_TEXTURE_BUFFER_SIZE: 134217728
Malt > GL_MAX_TEXTURE_COORDS: 8
Malt > GL_MAX_TEXTURE_IMAGE_UNITS: 32
Malt > GL_MAX_TEXTURE_LOD_BIAS: 15
Malt > GL_MAX_TEXTURE_MAX_ANISOTROPY: 16
Malt > GL_MAX_TEXTURE_SIZE: 32768
Malt > GL_MAX_TEXTURE_STACK_DEPTH: 10
Malt > GL_MAX_TEXTURE_UNITS: 4
Malt > GL_MAX_TRANSFORM_FEEDBACK_BUFFERS: 4
Malt > GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS: 128
Malt > GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS: 4
Malt > GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS: 4
Malt > GL_MAX_UNIFORM_BLOCK_SIZE: 65536
Malt > GL_MAX_UNIFORM_BUFFER_BINDINGS: 84
Malt > GL_MAX_UNIFORM_LOCATIONS: 65536
Malt > GL_MAX_VARYING_COMPONENTS: 124
Malt > GL_MAX_VARYING_FLOATS: 124
Malt > GL_MAX_VARYING_VECTORS: 31
Malt > GL_MAX_VERTEX_ATOMIC_COUNTERS: 16384
Malt > GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS: 8
Malt > GL_MAX_VERTEX_ATTRIBS: 16
Malt > GL_MAX_VERTEX_ATTRIB_BINDINGS: 16
Malt > GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET: 2047
Malt > GL_MAX_VERTEX_IMAGE_UNIFORMS: 8
Malt > GL_MAX_VERTEX_OUTPUT_COMPONENTS: 128
Malt > GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS: 16
Malt > GL_MAX_VERTEX_STREAMS: 4
Malt > GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS: 32
Malt > GL_MAX_VERTEX_UNIFORM_BLOCKS: 14
Malt > GL_MAX_VERTEX_UNIFORM_COMPONENTS: 4096
Malt > GL_MAX_VERTEX_UNIFORM_VECTORS: 1024
Malt > GL_MAX_VIEWPORTS: 16
Malt > GL_MAX_VIEWPORT_DIMS: [32768 32768]
Malt > GL_RGB8 GL_READ_PIXELS: GL_ZERO
Malt > GL_RGB8 GL_READ_PIXELS_FORMAT: GL_ZERO
Malt > GL_RGB8 GL_READ_PIXELS_TYPE: GL_UNSIGNED_BYTE
Malt > GL_RGB8 GL_TEXTURE_IMAGE_FORMAT: GL_ZERO
Malt > GL_RGB8 GL_TEXTURE_IMAGE_TYPE: GL_UNSIGNED_BYTE
Malt > GL_RGBA8 GL_READ_PIXELS: GL_FULL_SUPPORT
Malt > GL_RGBA8 GL_READ_PIXELS_FORMAT: GL_RGBA
Malt > GL_RGBA8 GL_READ_PIXELS_TYPE: GL_UNSIGNED_INT_8_8_8_8_REV
Malt > GL_RGBA8 GL_TEXTURE_IMAGE_FORMAT: GL_RGBA
Malt > GL_RGBA8 GL_TEXTURE_IMAGE_TYPE: GL_UNSIGNED_INT_8_8_8_8_REV
Malt > GL_RGBA GL_READ_PIXELS: GL_FULL_SUPPORT
Malt > GL_RGBA GL_READ_PIXELS_FORMAT: GL_RGBA
Malt > GL_RGBA GL_READ_PIXELS_TYPE: GL_UNSIGNED_INT_8_8_8_8_REV
Malt > GL_RGBA GL_TEXTURE_IMAGE_FORMAT: GL_RGBA
Malt > GL_RGBA GL_TEXTURE_IMAGE_TYPE: GL_UNSIGNED_INT_8_8_8_8_REV
Malt > GL_SRGB GL_READ_PIXELS: GL_ZERO
Malt > GL_SRGB GL_READ_PIXELS_FORMAT: GL_ZERO
Malt > GL_SRGB GL_READ_PIXELS_TYPE: GL_UNSIGNED_BYTE
Malt > GL_SRGB GL_TEXTURE_IMAGE_FORMAT: GL_ZERO
Malt > GL_SRGB GL_TEXTURE_IMAGE_TYPE: GL_UNSIGNED_BYTE
Malt > GL_SRGB_ALPHA GL_READ_PIXELS: GL_FULL_SUPPORT
Malt > GL_SRGB_ALPHA GL_READ_PIXELS_FORMAT: GL_RGBA
Malt > GL_SRGB_ALPHA GL_READ_PIXELS_TYPE: GL_UNSIGNED_INT_8_8_8_8_REV
Malt > GL_SRGB_ALPHA GL_TEXTURE_IMAGE_FORMAT: GL_RGBA
Malt > GL_SRGB_ALPHA GL_TEXTURE_IMAGE_TYPE: GL_UNSIGNED_INT_8_8_8_8_REV
Malt > GL_RGB16F GL_READ_PIXELS: GL_ZERO
Malt > GL_RGB16F GL_READ_PIXELS_FORMAT: GL_ZERO
Malt > GL_RGB16F GL_READ_PIXELS_TYPE: GL_HALF_FLOAT
Malt > GL_RGB16F GL_TEXTURE_IMAGE_FORMAT: GL_ZERO
Malt > GL_RGB16F GL_TEXTURE_IMAGE_TYPE: GL_HALF_FLOAT
Malt > GL_RGBA16F GL_READ_PIXELS: GL_FULL_SUPPORT
Malt > GL_RGBA16F GL_READ_PIXELS_FORMAT: GL_RGBA
Malt > GL_RGBA16F GL_READ_PIXELS_TYPE: GL_HALF_FLOAT
Malt > GL_RGBA16F GL_TEXTURE_IMAGE_FORMAT: GL_RGBA
Malt > GL_RGBA16F GL_TEXTURE_IMAGE_TYPE: GL_HALF_FLOAT
Malt > GL_RGB32F GL_READ_PIXELS: GL_ZERO
Malt > GL_RGB32F GL_READ_PIXELS_FORMAT: GL_ZERO
Malt > GL_RGB32F GL_READ_PIXELS_TYPE: GL_FLOAT
Malt > GL_RGB32F GL_TEXTURE_IMAGE_FORMAT: GL_ZERO
Malt > GL_RGB32F GL_TEXTURE_IMAGE_TYPE: GL_FLOAT
Malt > GL_RGBA32F GL_READ_PIXELS: GL_FULL_SUPPORT
Malt > GL_RGBA32F GL_READ_PIXELS_FORMAT: GL_RGBA
Malt > GL_RGBA32F GL_READ_PIXELS_TYPE: GL_FLOAT
Malt > GL_RGBA32F GL_TEXTURE_IMAGE_FORMAT: GL_RGBA
Malt > GL_RGBA32F GL_TEXTURE_IMAGE_TYPE: GL_FLOAT
Malt > --------------------------------------------------------------------------------
Malt > INIT PIPELINE: /home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/Pipelines/NPR_Pipeline/NPR_Pipeline.py
Malt > Traceback (most recent call last):
  File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Bridge/__init__.py", line 20, in start_server
    Server.main(pipeline_path, viewport_bit_depth, connection_addresses,
  File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Bridge/Server.py", line 296, in main
    pipeline = pipeline_class(plugins)
  File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/Pipelines/NPR_Pipeline/NPR_Pipeline.py", line 71, in __init__
    super().__init__(plugins)
  File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/Pipeline.py", line 44, in __init__
    graph.setup_reflection()
  File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/PipelineGraph.py", line 115, in setup_reflection
    src = self.preprocess_shader_from_source(src, [], ['VERTEX_SHADER','PIXEL_SHADER','REFLECTION'])
  File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/PipelineGraph.py", line 108, in preprocess_shader_from_source
    return shader_preprocessor(source, self.include_paths + include_paths, [self.get_material_define()] + defines)
  File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/GL/Shader.py", line 171, in shader_preprocessor
    raise Exception(result.stderr.decode('utf-8'))
Exception: /bin/sh: 1: /home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Malt/GL/../.Dependencies-39/mcpp-Linux: Permission denied

Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltPipeline.py", line 195, in depsgraph_update
    scene.world.malt.update_pipeline(bpy.context)

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltPipeline.py", line 54, in update_pipeline
    bridge = Bridge.Client_API.Bridge(path, int(self.viewport_bit_depth), debug_mode, renderdoc_path, plugin_dirs)

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/.MaltPath/Bridge/Client_API.py", line 99, in __init__
    params = self.connections['MAIN'].recv()

Blender > 
Blender >   File "/home/joe/building/blender-3.0.1-linux-x64/3.0/python/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()

Blender > 
Blender >   File "/home/joe/building/blender-3.0.1-linux-x64/3.0/python/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)

Blender > 
Blender >   File "/home/joe/building/blender-3.0.1-linux-x64/3.0/python/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError

Blender > 
Blender > EOFError

Blender > 
Blender > Traceback (most recent call last):

Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltNodes/MaltNodeTree.py", line 256, in track_library_changes

Blender >     
Blender > graphs = MaltPipeline.get_bridge().graphs
Blender > 

Blender > AttributeError
Blender > : 
Blender > 'NoneType' object has no attribute 'graphs'
Blender > 

Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 180, in track_shader_changes
    compiled_materials = MaltPipeline.get_bridge().receive_async_compilation_materials()

Blender > 
Blender > AttributeError: 'NoneType' object has no attribute 'receive_async_compilation_materials'

Blender > 
Blender > Traceback (most recent call last):

Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 152, in track_shader_changes

Blender >     
Blender > def track_shader_changes(force_update=False, async_compilation=True):
Blender > 

Blender > KeyboardInterrupt
Blender > 
Blender > 

Blender > Traceback (most recent call last):

Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltPipeline.py", line 265, in track_pipeline_changes

Blender >     
Blender > def track_pipeline_changes():
Blender > 

Blender > KeyboardInterrupt
Blender > 
Blender > 

Blender > Exception in module unregister():
Blender >  
Blender > '/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/__init__.py'
Blender > 

Blender > Traceback (most recent call last):

Blender > 
Blender >   File "/home/joe/building/blender-3.0.1-linux-x64/3.0/scripts/modules/addon_utils.py", line 439, in disable
    mod.unregister()

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/__init__.py", line 144, in unregister
    module.unregister()

Blender > 
Blender >   File "/home/joe/.config/blender/3.0/scripts/addons/BlenderMalt/MaltMaterial.py", line 213, in unregister
    bpy.app.timers.unregister(track_shader_changes)

Blender > 
Blender > ValueError: Error: function is not registered

B`

**Comment by pragma37** [comment]
This used to throw a PermissionError.
I have to investigate why that's no longer the case, but now it should work fine anyway.
Thank you for the report!
