### ISSUE TITLE
Is grey kinda transparent 

### ISSUE THREAD

**Issue by psychobee** [BlenderNPR/BEER#234]
### Malt version

latest 

### Blender version

blender 3.0.1

### OS

windows 10 / ubuntu

### Hardware info

intel i3 /  Intel® HD Graphics 4400 (HSW GT2)

### Issue description and reproduction steps

Previous  versions of malt did'nt work for me it showed a grey/transparent look for me in look dev and render mode .

But recently you fixed an issue for " RX480 8G: Unable to load numpy_formathandler accelerator from OpenGL_accelerate #227"  i tried using the that release it worked fine was getting yellow colour and white background . After installing the latest release the problem came back . Old release working fine but having issue with  latest   one .

 

### Attachments

[malt 2022-02-06(20-35).log](https://github.com/bnpr/Malt/files/8010497/malt.2022-02-06.20-35.log)

**Comment by pragma37** [comment]
Hi! This seems like the same issue reported in #232.
It should be fixed in the latest builds.
