### ISSUE TITLE
Malt Settings

### ISSUE THREAD

**Issue by josemoralescc** [BlenderNPR/BEER#235]
### Malt version

Development-latest

### Blender version

Blender 3.0.1

### OS

Ubuntu 20.04.3 LTS

### Hardware info

Intel i5-6200U / 8GB RAM / Intel HD Graphics 520

### Issue description and reproduction steps

The menus "Object Properties -> Malt Settings" and "Scene Properties -> Malt Settings" don't open.

![Screenshot from 2022-02-06 18-17-23](https://user-images.githubusercontent.com/21679398/152692611-abba6564-4111-4c34-acd5-658ea8b5c2b9.png)
![Screenshot from 2022-02-06 18-17-32](https://user-images.githubusercontent.com/21679398/152692613-21df7da5-4b68-44d1-8754-c06b606c4d8e.png)

### Attachments

Not session/file dependent.

**Comment by pragma37** [comment]
Hi! Thanks for the report.
This is not really a bug. It's just that there are no Malt specific scene or object properties at the moment.
I've updated the code to hide panels that are not used. (360526ab59465c48eaa5a5d2eb8c34003dce2eed)
