### ISSUE TITLE
On install, No module named 'OpenGL'

### ISSUE THREAD

**Issue by eballeste** [BlenderNPR/BEER#236]
### Malt version

Development-latest

### Blender version

3.2.0 Alpha

### OS

Windows 10 Pro 64bit

### Hardware info

Intel  i7-5930K | 48GB | Nvdia GTX-970

### Issue description and reproduction steps

On installation through preferences panel, I get:

ModuleNotFoundError: No module named 'OpenGL'

### Attachments

![installerror](https://user-images.githubusercontent.com/6924108/152698485-944848c5-be10-4254-a5b1-611b5b359506.png)

**Comment by pragma37** [comment]
Beta/Alpha Blender releases are not supported.
The Blender master branch has been recently updated to Python 3.10, so the Python libraries that ship with Malt are no longer compatible with those versions.
It's just a matter of updating the build scripts, but Malt already ships with libraries for 3.7 (Blender LTS) and 3.9(Blender 3.0).
Adding new versions increases the addon size considerably, so I would prefer to ship with as few as possible.

**Comment by eballeste** [comment]
gotcha, makes sense ✌️
