### ISSUE TITLE
Malt Nodes: changing MaltFunctionNode.name breaks node until node tree is updated

### ISSUE THREAD

**Issue by Kolupsy** [BlenderNPR/BEER#239]
### Malt version

Development (1.0.0.beta)

### Blender version

Blender 3.0.1

### OS

Win 10 64

### Hardware info

GeForce 2060 SUPER

### Issue description and reproduction steps

**Description:**
Renaming a node disables it or prevents it from updating (nodes added through global library get disabled, the `diffuse_gradient_shader` node does not update)

**How to reproduce:**
- Use clean file (no objects, Malt enabled)
- Add sphere and light
- Add material to sphere with new node tree
- Connect `diffuse_gradient_shader` and `MAIN_PASS_PIXEL_SHADER_Output` like this:
![image](https://user-images.githubusercontent.com/88381426/153010581-38069f85-c6f6-43ed-b090-064f346ef5d4.png)
- Rename the `diffuse_gradient_shading` node (changing the `name `attribute not the label)
- Adjust the color ramp
=> **Outcome:** the shading on the sphere does not change according to color ramp
![image](https://user-images.githubusercontent.com/88381426/153011207-8112be5b-96e0-4d78-aefa-81d00842eafc.png)

### Attachments

[malt 2022-02-08(15-53).log](https://github.com/bnpr/Malt/files/8024879/malt.2022-02-08.15-53.log)

**Comment by pragma37** [comment]
Yep, this is a known issue.
For now, you can force a shader recompilation with the reload button in the nodes header menu:
![imagen](https://user-images.githubusercontent.com/36610999/153230592-1abcca38-8c2a-4433-9736-17d7250d661f.png)

**Comment by Kolupsy** [comment]
I see. Would it be possible to label this button then. I was already wondering what that one and the one left of it were doing

**Comment by pragma37** [comment]
Done!
6f9c9bd1013e54bbbf8cf2207dacc3581cae0f7d
99760d3ed9708bb4cc0f45755a65482b45e63ec6
