### ISSUE TITLE
the materials examples file  is not showing in look dev and render mode and cant find main pass pixel shader output

### ISSUE THREAD

**Issue by psychobee** [BlenderNPR/BEER#241]
### Malt version

1.0 

### Blender version

blender 3.0.1

### OS

ubuntu 

### Hardware info

intel i 3 / ntel® HD Graphics 4400 (HSW GT2)

### Issue description and reproduction steps

![Screenshot from 2022-02-09 08-45-59](https://user-images.githubusercontent.com/21065506/153116467-2f4c4e36-a3e8-4ee3-8e96-ea1bf10eb609.png)
![Screenshot from 2022-02-09 08-47-54](https://user-images.githubusercontent.com/21065506/153116474-a5513ac9-bede-45e9-8d88-70c3f5e8428f.png)
![Screenshot from 2022-02-09 08-53-08](https://user-images.githubusercontent.com/21065506/153116477-86b4d7af-7ff8-440b-8935-beaf2f22d60f.png)
![Screenshot from 2022-02-09 08-54-01](https://user-images.githubusercontent.com/21065506/153116481-956f8f38-7084-4b6a-8e24-baa7d02b7ea1.png)

installed and opened your materials examples.blend file and it is showing yellow and not rendering  and cant see main _pass_pixel_shader_output  node.
i dont know if a log file would help but i am adding the log file too

### Attachments

[malt 2022-02-09(08-43).log](https://github.com/bnpr/Malt/files/8029175/malt.2022-02-09.08-43.log)

**Comment by pragma37** [comment]
Seems like you are trying to open the 1.0 Preview material examples in the Release version.
You need the Development version.
