### ISSUE TITLE
Shader function name confusion (specular_shading)

### ISSUE THREAD

**Issue by Kolupsy** [BlenderNPR/BEER#242]
### Malt version

Development (1.0.0.beta)

### Blender version

Blender 3.0.1

### OS

Win 10 64

### Hardware info

GeForce 2060 SUPER

### Issue description and reproduction steps

I am trying to write a shader function that uses the builtin function `specular_shading`. I was calling it like this:
```glsl 
vec3 specular = specular_shading( 1.0 );
```
but Malt kept complaining about conversion from flaot to vec3 although that could not be the case. Apparantly there are two functions called `specular_shading`, one with a lot of parameters and a simple one. I tried to call the simple one thought Malt thought it was the other. What can I do to be clear what kind of function I want to call? Is uniqueness a trait that all shader functions should follow of is there another way to distinguish functions with the same name?

![image](https://user-images.githubusercontent.com/88381426/153517861-56174a7b-c533-4527-8bcd-dc4947098c1f.png)

### Attachments

[malt 2022-02-11(00-58).log](https://github.com/bnpr/Malt/files/8045104/malt.2022-02-11.00-58.log)

**Comment by pragma37** [comment]
Where are you calling this function?
Is this a Material shader source file? A Node Tree local library? A plugin library?

Function overloading is a built-in GLSL feature, it's not related to Malt itself. If your driver shader compiler is complaining it's likely that *vec3 specular_shading(float roughness)*  is not available from wherever you are trying to call it.
Keep in mind that the simplified version is only available from Mesh shaders.

**Comment by Kolupsy** [comment]
Ok that clears it up. I was trying to write a shader function inside a plugin library and call the simplfied function in there. I guess this means that this issuse is now closed

**Comment by pragma37** [comment]
You **can** use the function in a plugin library, but only for Mesh shaders. So, in your *register_graph_libraries* function, instead (or in addition) of:

```python
for graph in graphs.values():
    if graph.language == 'GLSL':
        graph.add_library(library_path)
```

You simply do:
```python
graphs['Mesh'].add_library(mesh_library_path)
```
