### ISSUE TITLE
error when enabling malt

### ISSUE THREAD

**Issue by psychobee** [BlenderNPR/BEER#247]
### Malt version

latest dev version

### Blender version

blender 3.0.1

### OS

ubuntu

### Hardware info

intel i3 / Intel® HD Graphics 4400 (HSW GT2)

### Issue description and reproduction steps

After instaling malt when i press the tick mark this is the error it shows 
![Screenshot from 2022-02-12 07-43-27](https://user-images.githubusercontent.com/21065506/153692692-9a81a285-5f62-40da-bd77-2525da2e58ad.png)

### Attachments

no log file

**Comment by pragma37** [comment]
Have you maybe installed the Development version on top of the Release version?
Try to uninstall the addon first, then reinstall.

**Comment by psychobee** [comment]
I removed the old version and installed the dev version

**Comment by pragma37** [comment]
And it works now?
