### ISSUE TITLE
Adding COMMON_VERTEX_SHADER Input

### ISSUE THREAD

**Issue by Schofje** [BlenderNPR/BEER#248]
### Malt version

Release

### Blender version

3.0.1 Stable

### OS

W10 64 bit

### Hardware info

i5 6400 - RX480 8G - 32 GB ram

### Issue description and reproduction steps

Add vertex shader input node. Not file dependent.

### Attachments

[malt 2022-02-13(19-22).log](https://github.com/bnpr/Malt/files/8056334/malt.2022-02-13.19-22.log)
[Info log print.txt](https://github.com/bnpr/Malt/files/8056338/Info.log.print.txt)
![Screenshot 2022-02-13 192643](https://user-images.githubusercontent.com/49023943/153769144-208af53c-70c9-41ab-81b8-a838497f7f95.png)

**Comment by pragma37** [comment]
Can't reproduce it.
![imagen](https://user-images.githubusercontent.com/36610999/153775839-9e25cf6d-73fc-4264-873a-83826fb5eec3.png)

That's why I ask for a reproduction file.

**Comment by Schofje** [comment]
I tried to use it again. I apparently had a few buttons turned off. My bad for not properly giving a repro file!
