### ISSUE TITLE
Keep loading the MALT window

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#256]
### Malt version

Development-latest

### Blender version

Blender 3.01 and Blender 2.93

### OS

Windows 11 64bits

### Hardware info

Intel i5-9400F | 8 GB RAM | NVDIA GTX 1660 Ti

### Issue description and reproduction steps

Install the latest development version. enable MALT.
Then blender keeps loading the MALT window

https://user-images.githubusercontent.com/36077492/155259503-db7b44eb-7979-4f3f-b3ae-78932b29cb18.mp4

### Attachments

[malt 2022-02-23(11-59).log](https://github.com/bnpr/Malt/files/8121821/malt.2022-02-23.11-59.log)

**Comment by pragma37** [comment]
Seems like it was caused by a new PyOpenGL release (3.1.6).
I've patched the build scripts to stay in 3.1.5 for now. 44fe8e58776b555e48f88cfccb8ae357789fad4a
