### ISSUE TITLE
Is slower than cycles and hangs the system

### ISSUE THREAD

**Issue by psychobee** [BlenderNPR/BEER#257]
### Malt version

development version

### Blender version

blender 3.0.1

### OS

ubuntu  18

### Hardware info

intel i3 4 gb ram / Intel® HD Graphics 4400 (HSW GT2)

### Issue description and reproduction steps

computer  freezes if i render image  and is very slow overall . It takes around 4- 5 minutes to load even the look dev mode

### Attachments

[malt 2022-02-23(18-33).log](https://github.com/bnpr/Malt/files/8124605/malt.2022-02-23.18-33.log)

**Comment by pragma37** [comment]
This is not a bug report.
An integrated graphics processor from a 10 years old low-end Intel CPU doesn't meet the requirements to run Malt appropriately.
