### ISSUE TITLE
Print Malt Error

### ISSUE THREAD

**Issue by kuronekoshiii** [BlenderNPR/BEER#26]
![Print Malt Error](https://user-images.githubusercontent.com/75808214/101819091-bf290300-3b5f-11eb-96e0-c5dcad902b93.png)

I'm just putting materials then this happens, the other object that I didn't even click became a flat color, then when I clicked on that object the shader shows the error "Print Malt Error" then it became a chain reaction, the others as well became a default shader(empty/flat color, like when you just started and still not putting any material). even if you undo it, your project won't come back to its state before the error occurs.

**Comment by kuronekoshiii** [comment]
![Print Malt Error 2](https://user-images.githubusercontent.com/75808214/101819707-97866a80-3b60-11eb-9d11-9d866740dfdd.png)

and while trying to find a way to fix it, this happens. I thought my monitor has broken the heck! haha.  And it keeps getting worse while I'm trying to find a way.

**Comment by pragma37** [comment]
I need more info :

https://github.com/BlenderNPR/BEER/tree/master/BlenderMalt#bug-reports

**Comment by kuronekoshiii** [comment]
I clicked on an object then added material and I used the existing material, right after I chose the existing material the object that I'm texturing suddenly became yellow(Default Color that has no Shaders yet) and the screen splashes some grey lines like your monitor's LCD is broken. I quit the blender and use the autosave, but then the problem doesn't occur anymore.

**Comment by pragma37** [comment]
I'm closing this issue then.
There's little I can do without an error log or reproduction steps.
