### ISSUE TITLE
No nodes visible

### ISSUE THREAD

**Issue by ekswathi** [BlenderNPR/BEER#269]
### Malt version

all

### Blender version

Blender 3.1

### OS

windows 10 64 bit

### Hardware info

Intel I7 Nvdia 1060 6gb

### Issue description and reproduction steps

no rendering and can't add nodes in shader editor

### Attachments

Please have a look at this. I added the screenshots of the error. I am not able to add any nodes. and can't render
![image](https://user-images.githubusercontent.com/51689618/157803709-cb6f52f4-b511-413f-b206-310e4e57ade9.png)
![image](https://user-images.githubusercontent.com/51689618/157803982-bbd4d5d6-360a-43a7-a1a4-29574c32a2aa.png)
![image](https://user-images.githubusercontent.com/51689618/157804381-fc838378-0844-4031-8aff-3dc53867093b.png)

**Comment by pragma37** [comment]
Please, attach your session log, as requested in the [issue template](https://github.com/bnpr/Malt/blob/Development/.github/ISSUE_TEMPLATE/bug_report.yml).

**Comment by ekswathi** [comment]
I did it as per the issue template
