### ISSUE TITLE
Some objects can't join

### ISSUE THREAD

**Issue by kuronekoshiii** [BlenderNPR/BEER#27]
![image](https://user-images.githubusercontent.com/75808214/102009928-abef8080-3d75-11eb-9490-327e5e1ea0fa.png)

Even if I clicked both, the system is saying that no mesh data to join, but if I transfer it to another blender version, they can join. 

![image](https://user-images.githubusercontent.com/75808214/102010034-4c45a500-3d76-11eb-90bd-3d84e2f0518a.png)

I'm spamming ctrl + J on this one, they're not joining and the system doesn't seem to care as well, no errors just that they're not combining.

![image](https://user-images.githubusercontent.com/75808214/102010060-80b96100-3d76-11eb-8a6c-521f7286a246.png)

But it works when I tried to combine it with others.

**Comment by pragma37** [comment]
I seriously doubt this is related to Malt.
If you upload a simple blend file where I can reproduce the issue I can take a look.

**Comment by kuronekoshiii** [comment]
Sorry for the late reply, I'm busy at work. Apparently, I can combine them now, I think I just need to restart the blender. Gonna close this now sorry for that.
