### ISSUE TITLE
Not rendering

### ISSUE THREAD

**Issue by ekswathi** [BlenderNPR/BEER#270]
### Malt version

Latest development version

### Blender version

Blender 3.1

### OS

windows 10 64 bit

### Hardware info

Intel64,NVIDIA GeForce GTX 1060 6GB

### Issue description and reproduction steps

unable to add nodes and not rendering

### Attachments

[malt 2022-03-12(20-54).log](https://github.com/bnpr/Malt/files/8237856/malt.2022-03-12.20-54.log)
[malt test.zip](https://github.com/bnpr/Malt/files/8237857/malt.test.zip)

**Comment by pragma37** [comment]
The log shows the error: ```'CHCP' is not recognized as an internal or external command, operable program or batch file.```

CHCP is a built-in Windows System32 program. If the command ```where CHCP``` in the Windows cmd doesn't show the program location, your Windows installation is broken.

It also seems that you are using Blender 3.1 with a Python 3.9 version (?). The official Blender 3.1 release uses Python 3.10.

**Comment by ekswathi** [comment]
Thank you for quick response.  I will check and let you know

**Comment by Belf777** [comment]
![gg](https://user-images.githubusercontent.com/101658616/158423929-53cf04bf-53cc-49c2-a391-5e827d685feb.png)
hello, here is such a problem, the engine can be turned on but it does not render and there is always an error, what should I do? tell me please, thanks in advance

**Comment by pragma37** [comment]
@Belf777 Open a new issue with the required info.

**Comment by ekswathi** [comment]
I installed persistent module and it worked.  Thank you
