### ISSUE TITLE
Extreme Lag + Shaders not working on macOS

### ISSUE THREAD

**Issue by SadakoxD** [BlenderNPR/BEER#28]
In rendered view, I experience massive lag - making the render engine impossible to use.

**My specs:
Blender version: 2.91.0 (2.91.0 2020-11-25)
Computer: iMac 2013 / 3.1 GHz intel core i7 / 16 GB RAM / NVIDIA GeForce GT 750M 1 GB
OS: macOS Mojave 10.14.6**

Also, some shaders don't work as expected:

**basic_line.mesh.glsl ERROR:**

NPR_Pipeline : PRE_PASS : SHADER LINKER ERROR :
WARNING: Output of vertex shader 'MODEL' not read by fragment shader
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 19 samplers
NPR_Pipeline : MAIN_PASS : SHADER LINKER ERROR :
WARNING: Output of vertex shader 'MODEL' not read by fragment shader
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 21 samplers
NPR_Pipeline : SHADOW_PASS : SHADER LINKER ERROR :
WARNING: Output of vertex shader 'MODEL' not read by fragment shader
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 17 samplers

I would so love to use this render engine. Please continue working on it for your Mac friends as well :)

**Comment by pragma37** [comment]
Hi. Sorry but looks like you graphics card only supports 16 textures per shader, while most GPUs (even your GPU running on Windows) support 32.

I have to optimize the number of texture units used by the engine, but even then I doubt it will ever be practical to use it with only 16 units.

**Comment by SadakoxD** [comment]
thanks for the quick answer.

Q_Q oh no. 

Well, I was planning on buying a new Mac next year. But how do I know it will support this number? Or asked differently: Does the current / newest iMac (Radeon Pro 555X // 560X) support that?

**Comment by pragma37** [comment]
Can't say for sure if the new iMac would work.
I'm actually surprised that yours doesn't since as I said seems like your GPU supports it on other operative systems, but Apple has been passive-aggressively discouraging the use of OpenGL on their platforms since they released Metal.
