### ISSUE TITLE
Blender 3.1.2 freezes when switching to Malt render engine

### ISSUE THREAD

**Issue by Tanya0009** [BlenderNPR/BEER#288]
### Malt version

1.0.0 Beta

### Blender version

Blender 3.1.2

### OS

Windows 10 64 bit

### Hardware info

Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz | 16 gb ram | GTX 1660 TI

### Issue description and reproduction steps

Hi, so when i installed the add on and enabled it then went to change the render engine to malt, Blender freezes for years 

### Attachments

couldnt find it but to reporduce the error just switch to malt

**Comment by pragma37** [comment]
I just tested this with a fresh Blender 3.1.2 download and the latest Malt development version and it works just fine.

> couldnt find it but to reporduce the error just switch to malt

What does this mean? What happens when you go to `Preferences > Addons > BlenderMalt > Open Session Log` ?
