### ISSUE TITLE
LAG: Update to latest nvidia drivers!

### ISSUE THREAD

**Issue by SememeS** [BlenderNPR/BEER#29]
This is both a warning for a problem with a solution included.

PC: Laptop with Geforce rtx 2060m / i7 10750H / 16gRAM

Was having serious lag(unusable) when picking a shader for a material

Updated drivers to latest nvidia drivers( in my case now latest 460.89)

No more lag

Thanks for your hard work BlenderNPR team!

**Comment by pragma37** [comment]
Noted. Thanks for reporting!
