### ISSUE TITLE
line-test file not rendering in viewport

### ISSUE THREAD

**Issue by ianBIT** [BlenderNPR/BEER#299]
### Malt version

latest version

### Blender version

Blender 3.12

### OS

windows 10 64bits

### Hardware info

amd 3900x 32gb ram Rtx 3090

### Issue description and reproduction steps

render view from this file results in a non-rendered image in viewport -  the object disappears

i also have the same problem with a Gigabyte areo 17 hdr laptop - 3070 gpu - 32 gig ram  win10

### Attachments

[line_id_mask.zip](https://github.com/bnpr/Malt/files/8691589/line_id_mask.zip)

**Comment by pragma37** [comment]
Please, read the attachment instructions:
https://github.com/bnpr/Malt/blob/Development/.github/ISSUE_TEMPLATE/bug_report.yml

You are missing the most important info.

Also, indicate if the error happens on any file or just in the line id example.

**Comment by ianBIT** [comment]
only happens with your file, blank viewport no errors

**Comment by ianBIT** [comment]
actually i just tested your "preview examples" file also - it does not
display in render window either
only 1 out of my four pc computers work with any of your files  , but when
i do my own work with the nodes it seems to work on my other computers -
there must be a setting button i have not turned on someplace

very strange
