### ISSUE TITLE
GLSL mesh shaders produces error 

### ISSUE THREAD

**Issue by Bstyun** [BlenderNPR/BEER#300]
### Malt version

April 13, 2022 release

### Blender version

3.1.2

### OS

Windows 10 64 bit

### Hardware info

AMD Ryzen 7 3700U / 8gb ram / Radeon RX Vega 10 Graphics

### Issue description and reproduction steps

My first time trying malt and I receive this error when trying out the basic mesh shader
![image](https://user-images.githubusercontent.com/95403189/168476258-9fccb80d-3813-49c2-bad4-58c3afaebf0a.png)

It seem to be the same issue with #193 but the fix in there didnt work for me
Also tried the other mesh shaders and all showed the same issue

### Attachments

[malt 2022-05-15(21-39).log](https://github.com/bnpr/Malt/files/8695083/malt.2022-05-15.21-39.log)

**Comment by pragma37** [comment]
You are trying to use the pre-1.0 shaders in the 1.0 version.
(Not sure why? They are no longer in the release downloads)

These are the new (node based) examples: https://github.com/bnpr/Malt/discussions/94#discussioncomment-2117754

**Comment by Bstyun** [comment]
Ah there we go!
Sorry about that 
I was following the instructions here https://bnpr.gitbook.io/beer-malt-wiki/ and didnt know that the sample files are outdated

All's working now
Thank you!
