### ISSUE TITLE
SHADER ERROR

### ISSUE THREAD

**Issue by Badteist** [BlenderNPR/BEER#302]
### Malt version

1.0.0 beta

### Blender version

3.1.0

### OS

windows 11 64 bits

### Hardware info

intel i5-10300 | 16 GB RAM | Nvidia GTX 1650 Ti 4GB

### Issue description and reproduction steps

i just install the render engine and i can't use the shaders.

### Attachments

![image](https://user-images.githubusercontent.com/91920122/169939260-d38f2ed8-468c-450e-b14a-7ed72edeb3df.png)

**Comment by pragma37** [comment]
I guess you are following this heavily outdated video? (https://www.youtube.com/watch?v=tnXnmcC49iU)

Take a look at my answer here:
https://github.com/bnpr/Malt/issues/300#issuecomment-1126950272
