### ISSUE TITLE
Adding new scene to current file makes blender not respond everytime you do something

### ISSUE THREAD

**Issue by Psi25** [BlenderNPR/BEER#306]
### Malt version

1.0.0 beta

### Blender version

3.1.0

### OS

Windows 10 Pro

### Hardware info

Amd Ryzen 7 1700X, 16GB RAM, Nvidia GTX 1660

### Issue description and reproduction steps

1| create new blend file
2| set engine to malt. add some objects in the default scene and tweak some sharers. 
3| add new scene
4| set engine to malt
5| do something like adding an object then moving it
6| blender lags with the cursor loading thing

### Attachments

[malt 2022-05-28(13-08).log](https://github.com/bnpr/Malt/files/8790523/malt.2022-05-28.13-08.log)
[linetest01.blend](https://drive.google.com/file/d/1OZjjC1oKv7UGkHdUJeFROb4Dx6FyURml/view?usp=sharing)

**Comment by pragma37** [comment]
Malt needs a World to work, and new Scenes don't have a World by default.

However, this shouldn't cause any performance issues and I can't reproduce them on my end.

I'll try to find a better way to handle this, but for now, just make sure that your scene has a World assigned when using Malt.

**Comment by Psi25** [comment]
> Malt needs a World to work, and new Scenes don't have a World by default.

That explains why. I will wait the next update when this issue is resolved.
