### ISSUE TITLE
Viewport not displaying render preview 

### ISSUE THREAD

**Issue by MarkN-B** [BlenderNPR/BEER#309]
### Malt version

Latest Release 

### Blender version

Blender 3.1.2

### OS

Windows 10

### Hardware info

Intel i7-8700 | 16GB Ram 

### Issue description and reproduction steps

After downloading malt for the first time and switching to render, no textures display and the object appears invisible. 

I have Included a picture of what is happening, this is a brand new blender file and the only things I have changed are the render engine, (from eevee to malt) switching the viewport mode to render, and changing the cube material to "Default mesh"

Thank you for the assistance.

![170987016-1828df3c-fbb3-4972-88c9-e3f4d4b5db1f](https://user-images.githubusercontent.com/106532243/171208793-c7db2918-938a-4e36-99a9-90b8a67a81ef.png)
 

### Attachments

[malt 2022-05-31(17-22).log](https://github.com/bnpr/Malt/files/8806508/malt.2022-05-31.17-22.log)

**Comment by pragma37** [comment]
The log doesn't show any errors.
Is that log from a session where the error happened?

If it is, does the Material Properties panel show any error?
Like this:
![imagen](https://user-images.githubusercontent.com/36610999/171654939-5eb00fa8-c118-4b82-8482-f385022506f2.png)
