### ISSUE TITLE
Strange render with object with multiple material and decimate modifier

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#312]
### Malt version

Development-latest

### Blender version

Blender 3.1.2

### OS

Windows 11 64bits

### Hardware info

Intel i5-9300H | 8 GB RAM | NVDIA GTX 1650

### Issue description and reproduction steps

1. Create a object, 
2. Assign two materials (could be the same) to different area
![image](https://user-images.githubusercontent.com/36077492/171635966-f22d9b93-b541-4aab-8c39-8b69c01b88bd.png)
3. Go to modifier, choose a decimate, then drag down the ratio, the render is strange
![image](https://user-images.githubusercontent.com/36077492/171636436-269532fa-3c20-4f75-b7e8-b0c284e5db65.png)
4. delete one of the material (even though both are the same) the render error disappear

### Attachments

[test2.zip](https://github.com/bnpr/Malt/files/8824058/test2.zip)

**Comment by pragma37** [comment]
Thank you for the detailed report. It should be fixed now. :)
