### ISSUE TITLE
Another render error with object with multiple materials and decimate modifier

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#313]
### Malt version

Development-latest

### Blender version

Blender 3.1.2

### OS

Windows 11 64bits

### Hardware info

Intel i5-9300H | 8 GB RAM | NVDIA GTX 1650

### Issue description and reproduction steps

1. assign at least 2 materials to an object
2. drag the decimate modifier ratio to 0
3. change the ratio back to any non-zero value, the render becomes transparent
![image](https://user-images.githubusercontent.com/36077492/171781745-609fbb9b-2ddc-4c90-a39f-e0c3a03fdd1e.png)

### Attachments

[test5.zip](https://github.com/bnpr/Malt/files/8829364/test5.zip)

**Comment by HSDSZ** [comment]
This bug only appears in the latest development version. I test the latest release version, everything is fine

**Comment by pragma37** [comment]
Fixed! Thank you.
