### ISSUE TITLE
background rendering issue 

### ISSUE THREAD

**Issue by buttabean** [BlenderNPR/BEER#32]
When you try to render out a background instance, whether it's a frame or animation, it seems to not render properly.

**Comment by BlenderNPR** [comment]
We need more info to solve your problem.

Please include:

    A System Info report generated by Blender (Help > Save System Info).
    A full copy of the System Console contents (Window > Toggle System Console).
    A .blend file and a list of steps to reproduce the error.

**Comment by buttabean** [comment]
I'm running windows 10 64bit with a nvidia 3090rtx. I suspect the 3090 might be causing issues.

It'll render fine in the viewport but not as a background instance.

I created a new file. Added the example shader to the default cube's material. Renders fine in blender viewport and also when I click render.

If I open the command prompt, direct it to the root of my blender build  and type the following 

blender.exe -b p2.blend -f 1

Must place the p2.blend into your blender folder or you'll have to add the path to the file into the command. example blender.exe -b I:\p2.blend -f 1

click enter to run the command and it'll render as if I did not attach a example shader file to the material of the model.

In the command prompt I noticed this error only when running the render as a background instance:

OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenBuffers, check for bool(glGenBuffers) before calling
Unable to load numpy_formathandler accelerator from OpenGL_accelerate

system console contents:
Read prefs: A:\SteamLibrary\steamapps\common\Blender\2.91\config\userpref.blend
found bundled python: A:\SteamLibrary\steamapps\common\Blender\2.91\python
Read blend: I:\p2.blend
Unable to load numpy_formathandler accelerator from OpenGL_accelerate
Info: Saved "p2.blend"

https://drive.google.com/file/d/1o4sWIaRUqW5jiIJbEVd2ImZgZBCev7Mb/view?usp=sharing here's the system info and blend file.

It's strange that it'll render within blender but not as a background instance.

**Comment by pragma37** [comment]
> it'll render as if I did not attach a example shader file to the material of the model.

Does it render correctly if you open the blend file located in the same folder as Blender?
If you added the example shader as a relative path and then you moved your blend file, the shader path is no longer correct.

**Comment by buttabean** [comment]
> > it'll render as if I did not attach a example shader file to the material of the model.
> 
> Does it render correctly if you open the blend file located in the same folder as Blender?
> If you added the example shader as a relative path and then you moved your blend file, the shader path is no longer correct.

Hmm. so i moved the shader example and blend file to the root of blender than opened the blender file in blender. It no longer had the blendermalt addon activated. I had to reinstall malt in blender.  activate malt, then setup the shader to the material. works in viewport and it will render. Does not render correctly as a background instance.

**Comment by pragma37** [comment]
Should be fixed now. (6d69ec04049e2d054f0dce9206ae378b8c09c27b)

Could you try the latest version and tell me if that works for you?

**Comment by buttabean** [comment]
> Should be fixed now. ([6d69ec0](https://github.com/BlenderNPR/BEER/commit/6d69ec04049e2d054f0dce9206ae378b8c09c27b))
> 
> Could you try the latest version and tell me if that works for you?

Fantastic, it's fixed. Thank you
