### ISSUE TITLE
Access violation error when trying to render

### ISSUE THREAD

**Issue by Kolupsy** [BlenderNPR/BEER#322]
### Malt version

Development

### Blender version

Blender 3.2

### OS

Windows 10 64

### Hardware info

GeForce 2060 SUPER

### Issue description and reproduction steps

When rendering using Malt in Blender 3.2, Malt throws an OSError exception with an access violation.
I am not 100% sure this is not tied to the setup that I have but I tried to use Malt as vanilla as possible, using developement branch, no plugins, no app templates. You can see the console output below

![image](https://user-images.githubusercontent.com/88381426/172849575-eb4cb127-38b1-4df3-ba35-f1bd40f2075b.png)

Reproduction:
- Open Blender 3.2
- Enable Malt
- have a mesh object in your scene
- switch to rendered view
-> Console spits out OSError

### Attachments

should be file independant

**Comment by pragma37** [comment]
Are you maybe using a Blender 3.2 pre-release version?

I've just tried a fresh 3.2 portable install and BlenderMalt downloaded from Github and it seems to be working fine.

Try posting the log file, maybe there's something relevant.

**Comment by Kolupsy** [comment]
I used the installer release version of 3.2 (you can see in the lower-right corner of the screenshot). I am going to try with a portable version but that would be weird if that would make any difference

**Comment by Kolupsy** [comment]
Turned out I had to rebuild Malt make to make it work since downloading the addon worked fine in otherwise. I figured in hindsight that when header files get updated (like they did) that a rebuild would probably be necessary.
