### ISSUE TITLE
xxHash module not found

### ISSUE THREAD

**Issue by Kolupsy** [BlenderNPR/BEER#338]
### Malt version

Development 1.0.0.beta.2

### Blender version

Blender 3.2

### OS

Windows 10 64

### Hardware info

GeForce 2060 SUPER

### Issue description and reproduction steps

When I try to open Malt using the commit (and upwards) of the xxhash module being added to malt, Blender throws a ModuleNotFoundError on registering. I saw that there was supposed to be a PIP install to load this module but it seems BlenderMalt tries to import the module before the PIP install.

### Attachments

![image](https://user-images.githubusercontent.com/88381426/175367545-da0d45eb-7e56-4563-a791-a3be8fec6ea7.png)

**Comment by pragma37** [comment]
The installation runs as part of the BlenderMalt building script.
If you are using Malt directly from source, you have to run intall_dependencies.py manually.
(Run it with the Blender built-in Python executable to ensure the version installed matches)

**Comment by Kolupsy** [comment]
Ah I see. Yes, worked beautifully!

**Comment by ColonelThirtyTwo** [comment]
This is happening to me when I try to enable BlenderMalt in the addons menu, after installing BlenderMalt-Linux.zip from the releases tab (commit c9604b0de60d8074a41931c54e84c47ccbce5666) on Blender 3.5.1 in Arch Linux.

**Comment by pragma37** [comment]
@ColonelThirtyTwo Please, open a new issue.
If you have downloaded the addon from the GitHub release it must be a different problem.
