### ISSUE TITLE
Shader Examples do not work on fresh install (system: Manjaro Linux)

### ISSUE THREAD

**Issue by NovikovPrinciple** [BlenderNPR/BEER#35]
System: [Linux] **Manjaro Nibia 20.2**
Blender version: **2.91.0** (build date: 2020-11-25)
OpenGL version: **4.6** (Compatibility Profile) Mesa 20.2.3

[bug-report.zip](https://github.com/BlenderNPR/BEER/files/5754228/bug-report.zip)

Steps to reproduce:
1. Use Manjaro package manager to get a fresh install of Blender.
2. Download 'BlenderMalt-Linux.zip'  and 'Shader-Examples.zip' from v1-beta.
3. Extract 'Shader-Examples' to its own folder.
4. Open Blender, install add-on via Preferences.
5. Enable BlenderMalt add-on.
6. Change render engine (Render Properties > Render Engine > Malt).
7. Change View Transform (Render Properties > Color Management > Filmic).
8. Change Light type from 'Point' to 'Sun'.
9. Delete default cube. Create Icosphere (Subdivisions: 4. Shaded Smooth).
10. Create new Material for Icosphere
11. Set 'Shader Source': Using UI, navigate to extracted 'Shader-Examples' folder. Select 'basic.mesh.glsl'.

Error message (from 'Print Malt error'): 

> NPR_Pipeline : PRE_PASS : SHADER COMPILER ERROR :
0:4(1): error: syntax error, unexpected invalid token
SHADER COMPILER ERROR :
0:4(1): error: syntax error, unexpected invalid token
SHADER LINKER ERROR :
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shaderNPR_Pipeline : MAIN_PASS : SHADER COMPILER ERROR :
0:4(1): error: syntax error, unexpected invalid token
SHADER COMPILER ERROR :
0:4(1): error: syntax error, unexpected invalid token
SHADER LINKER ERROR :
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shaderNPR_Pipeline : SHADOW_PASS : SHADER COMPILER ERROR :
0:4(1): error: syntax error, unexpected invalid token
SHADER COMPILER ERROR :
0:4(1): error: syntax error, unexpected invalid token
SHADER LINKER ERROR :
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader

**Comment by pragma37** [comment]
Not sure what's going on there.

The shader compiler complains about an invalid token at the line 4 of the shader, but it doesn't print any token and the line 4
of the basic example should be an empty line.
https://github.com/BlenderNPR/BEER/blob/master/Malt/Shader%20Examples/basic.mesh.glsl#L4

There are also some OpenAL and LLVM related errors in your log. Looks like an OS/driver issue.

**Comment by NovikovPrinciple** [comment]
> ...
> There are also some OpenAL and LLVM related errors in your log. Looks like an OS/driver issue.

Yeah, I'm assuming that, too. As far as my distro is concerned, the 'mesa' libraries are up-to-date. Same with the Radeon libraries. I even installed the 'python-opengl' library just in case, but the console logs were still as above.

I'll wait until the Manjaro distribution updates to a newer version of Blender (once it comes out). In the meanwhile, I might try writing my own shader for the pipeline, but learning shaders in general **along with** the Malt Pipeline is going to take some time.

**Comment by pragma37** [comment]
> I'll wait until the Manjaro distribution updates to a newer version of Blender

Have you tried with the official download from the Blender website ?

https://www.blender.org/download/

**Comment by NovikovPrinciple** [comment]
Yes, I tried that also. The results were the same, but I'm not entirely sure the Blender "install" was isolated from the rest of my system when I ran it, since I just extracted it from the downloaded file.

I still believe this issue is system-related though, and less relevant to the Blender-side of things, so I think this issue can be closed if there's no further comment.

**Comment by pragma37** [comment]
Ok. I'm closing it.

Please comment if it gets fixed.
