### ISSUE TITLE
Incorrect TIFF image sampling

### ISSUE THREAD

**Issue by Kolupsy** [BlenderNPR/BEER#370]
### Malt version

Development 1.0.0.beta.2

### Blender version

Blender 3.2

### OS

Windows 10 64

### Hardware info

GeForce 2060 SUPER

### Issue description and reproduction steps

Malt seems to sample TIFF (.tif) textures incorrectly. They are darker than they are supposed to be. Example in attchments. You can see in comparison how it is supposed to look like. I observed this issue with different TIFF images whereas other formats like PNG behave correctly.

### Attachments

![image](https://user-images.githubusercontent.com/88381426/182846726-d2d12af0-9030-46ea-aee4-62c317759a99.png)

**Comment by pragma37** [comment]
I can't reproduce it.

![imagen](https://user-images.githubusercontent.com/36610999/182887356-4d5063ab-df0c-4366-bc66-66371340fa3a.png)

Could it be related to the color management settings or the image itself?

**Comment by Kolupsy** [comment]
I'll send the file in a minute. Color management is sRGB which should be correct. Other color management settings are incorrect either

**Comment by Kolupsy** [comment]
[broken_tiff_example.zip](https://github.com/bnpr/Malt/files/9262282/broken_tiff_example.zip)

**Comment by pragma37** [comment]
Hope this is **finally** fixed.

**Comment by Kolupsy** [comment]
![image](https://user-images.githubusercontent.com/88381426/182952905-0f81a278-8957-4f04-b0df-2e604a6679ad.png)

huzzah!
