### ISSUE TITLE
Node UX branch: shader compiler error

### ISSUE THREAD

**Issue by CG-GeisT** [BlenderNPR/BEER#384]
### Malt version

node-ux-latest

### Blender version

Blender 3.2.2

### OS

voidlinux x86_64

### Hardware info

ryzen 7 2700x | 16 gb of ram | rx580 8gb OC

### Issue description and reproduction steps

Hi, I've been following the development of malt's UX branch because I've been waiting for an opportunity to try it. But I've run into an error that's keeping me from tinkering around.

After installing the new ux version of malt, I switched the render engine to malt and created a new node tree for a material. Upon assigning the tree to the material, I am greeted with a “PRE_PASS: SHADER COMPILER ERROR” message. As for the viewport, nothing is rendered.

To make sure that it wasn't something wrong with my blender install, I removed the ux branch version and installed the Development-latest version. The development version seems to work without errors.

### Attachments

Node-ux-latest
[malt 2022-08-20(22-12).log](https://github.com/bnpr/Malt/files/9388327/malt.2022-08-20.22-12.log)
![image](https://user-images.githubusercontent.com/68447848/185773087-c59b51c9-81b5-41ac-aa69-884c5781ed4d.png)

 Development-latest
![image](https://user-images.githubusercontent.com/68447848/185773878-c24600e2-8e53-4daf-b846-ad33ca98c939.png)

**Comment by pragma37** [comment]
This is more an issue with your driver shader compiler being extremely picky, to the point of actually being wrong.

It gives a lot of false warnings about using initialized variables and reports as an error an implicit conversion from int to a float, which is actually valid GLSL.
https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Implicit_conversion

I've "fixed" it, since it doesn't really cause any harm, but if I were you I would look into a better driver.

**Comment by CG-GeisT** [comment]
Thanks for the quick response!

I've tested the fix, and It got rid of the error from before, but I'm still unable to see anything in the viewport. Although not as long as before, malt still throws an error.

[malt 2022-08-22(22-55).log](https://github.com/bnpr/Malt/files/9399056/malt.2022-08-22.22-55.log)
![image](https://user-images.githubusercontent.com/68447848/186061327-ba5c2892-490d-4457-87b6-43deae2b2a2a.png)

> This is more an issue with your driver shader compiler being extremely picky, to the point of actually being wrong.
> If I were you I would look into a better driver.

Unfortunately, I'm using the mesa package for my Linux distro (mesa 22.1.7_1), and voidlinux doesn't support AMD's Pro drivers, so I can't switch. I'm not sure if this only happens with this version of mesa, or if other distros' mesa packages have the same behavior.

**Comment by pragma37** [comment]
Could you show me what `/tmp/.maltautogenerated/defaultsBackground Node Tree.screen.glsl` looks like?
The compiler is complaining about an undeclared identifier in that file.

**Comment by CG-GeisT** [comment]
> Could you show me what /tmp/.maltautogenerated/defaultsBackground Node Tree.screen.glsl looks like?

Does this work?

#include "NPR_ScreenShader.glsl"
#include "Node Utils 2/node_utils_2.glsl"
#include "Node Utils/node_utils.glsl"




layout (location = 0) out vec4 OUT_SCREEN_SHADER_COLOR;
uniform vec4 U_0_Background_0_v;
uniform sampler2D IN_SCREEN_SHADER_COLOR;
uniform vec2 U_0_Image_0_UV;
uniform bool U_0_Image_0_Smooth_Interpolation;


#ifdef PIXEL_SHADER
void SCREEN_SHADER()
{
	vec4 _Background_0_result = Vec4_color_property(U_0_Background_0_v);


	vec4 _Image_0_Color;
	vec2 _Image_0_Resolution;
	Image(IN_SCREEN_SHADER_COLOR,UV[0],U_0_Image_0_Smooth_Interpolation,_Image_0_Color,_Image_0_Resolution);

	OUT_SCREEN_SHADER_COLOR = _Layer_Blend_0_result;

}
#endif //PIXEL_SHADER

**Comment by CG-GeisT** [comment]
I've just Tested the latest version of the ux branch
Looks like everything works so far, Time to start testing it out!

![image](https://user-images.githubusercontent.com/68447848/186437115-2f155e47-9806-414b-a387-aaaed3cfa12c.png)

Should I close the issue?

**Comment by pragma37** [comment]
Good!
I'm not sure what could have caused your second issue, but I'm glad it works now. 👍
