### ISSUE TITLE
Artefacts using basic_gradient.mesh.glsl shader

### ISSUE THREAD

**Issue by TahsinTariq** [BlenderNPR/BEER#39]
I just installed BEER and got these weird gradients.

![image](https://user-images.githubusercontent.com/62146852/103475867-34909800-4ddb-11eb-82b0-00f49b599e7a.png)

**Comment by pragma37** [comment]
Can't reproduce it.

Could you post more info and attach the blend file?
https://github.com/BlenderNPR/BEER/tree/master/Malt#bug-reports

**Comment by TahsinTariq** [comment]
https://drive.google.com/drive/folders/1RR0ZYttOxUjO4q6pX51H_W-86PPQ26LO?usp=sharing

I've added the system-info and a console.txt. 
In the console, `Warning: 'PT_Tessellate' doesn't contain '_PT_' with prefix & suffix` is showing because I'm working on a python script.

Don't know about the `Unable to load numpy_formathandler accelerator from OpenGL_accelerate` part though.

Steps I did:
 - delete default cube and add an icosphere with 3 subdiv.
 - change default light to sun
 - change renderer to MALT and add material source basic_gradient.mesh.glsl
 - change the dark specular gradient to a lighter color... this seems to always create artefacts.

**Comment by pragma37** [comment]
Oh! I see.

Yes, that's expected. The left side of the ramp should always be black.
Otherwise you are still adding a specular color even when the specular value is 0.

Those artifacts you see are caused by self-shadows, but they wouldn't be visible with a correct color ramp.
