### ISSUE TITLE
PPO.id Shader Compilation error on Node Groups Branch

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#396]
### Malt version

Node Groups

### Blender version

Blender 3.3

### OS

Windows 10 64x

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

Plugging anything into the Pre Pass Pixel Shader ID input returns the compilation error found in the following log.

[malt 2022-09-22(09-55).log](https://github.com/bnpr/Malt/files/9627090/malt.2022-09-22.09-55.log)

Only occurs on the Node Groups branch. 

### Attachments

[Pack ID Compilation Error.zip](https://github.com/bnpr/Malt/files/9627098/Pack.ID.Compilation.Error.zip)

**Comment by pragma37** [comment]
Good catch! Thank you.

Should be fixed now.
