### ISSUE TITLE
Renaming a node group kill most of the nodes

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#402]
### Malt version

node-groups-latest

### Blender version

Blender 3.30

### OS

Windows 11 64bits

### Hardware info

Intel i5-9400F | 8 GB RAM | NVDIA GTX 1660 Ti

### Issue description and reproduction steps

before renaming
![image](https://user-images.githubusercontent.com/36077492/192551681-d2a924e9-c7b1-4efe-bb3e-a065b80889ac.png)

After renaming the node group

![image](https://user-images.githubusercontent.com/36077492/192551801-c6bed7d9-d4de-44da-80f1-4a74ed00164a.png)

### Attachments

[untitled.zip](https://github.com/bnpr/Malt/files/9656792/untitled.zip)

**Comment by pragma37** [comment]
Should be fixed. Thanks!
