### ISSUE TITLE
Blender Crashes upon using edit Node Tree operator when no tree is selected

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#405]
### Malt version

Node Groups

### Blender version

Blender 3.3

### OS

Windows 10 64x

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

Blender will crash upon a using the Edit Node Tree operator found on the Node Group node.

Maybe it'd be best to replace the selector there with the selector found on the screen pass and material? Since you shouldn't really be able to edit nothing anyways. That's avoided in those instances since it only shows up *after* selecting/creating a node tree.
![image](https://user-images.githubusercontent.com/31767887/192647370-0d9e2867-50dc-4bac-bc29-0c35f62eca25.png)

### Attachments

No relevant log/blend to attatch.

**Comment by pragma37** [comment]
I  updated the node so the edit button is not available if there's no group.
Thanks! 👍
