### ISSUE TITLE
Noodle becomes unusable after connecting to incompatible outputs.

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#406]
### Malt version

Node Groups and Development

### Blender version

Blender 3.3

### OS

Windows 10 64x

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

When an output to input connection is invalid we get a specific red noodle color with a line in the middle of it.
![image](https://user-images.githubusercontent.com/31767887/192648169-d3027ce2-f2e9-48b0-b891-20f5a5dd4e88.png)

However, if you immediately drag it from that input to a more sensible one, the connection still will not work.
![image](https://user-images.githubusercontent.com/31767887/192648280-0815b14a-be3a-4bb8-b8af-d4f7574b30e4.png)

To work around this, you have to disconnect the noodle entirely, and plug it into the correct one.

This also happens when dragging and dropping nodes on top of one another. (Side note: Might be a good idea to add some sort of priority system to what input goes where when dragging and dropping, most of the time when you're dragging and dropping a Color Ramp onto something you aren't gonna want to use the sampler1d input, but rather the U, UVW, or UVWX ones.)

### Attachments

No relevant log/blend

**Comment by pragma37** [comment]
I noticed that as well.
I fixed this at some point, but the issue was reintroduced after optimizing some of the code.
