### ISSUE TITLE
Node Groups fail to compile when Plugins are loaded

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#409]
### Malt version

Node Groups

### Blender version

Blender 3.3

### OS

Windows 10 64x

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

Simply have a plugin installed, such as the example plugin (https://github.com/bnpr/Malt/tree/Development/plugins/PluginExample). Upon reloading the pipeline, and plugging in a Node Group to a pass output, vertex and fragment shaders fail to compile, stating that the "Function already has a body".

Unplug it and everything works fine. You don't need a plugin to be *in* the node group for shader compilation to fail. 

### Attachments

[Uploading malt 2022-09-29(19-04).log…]()

**Comment by pragma37** [comment]
Thanks! Should be fixed now.

Keep an eye when you upload an attachment, btw. Sometimes Github breaks the link.
