### ISSUE TITLE
malt error at first test

### ISSUE THREAD

**Issue by ortocurvo** [BlenderNPR/BEER#41]
[blender]

2.91 on mac. just installed the add on added basic material from material samples and i receive this error

![image](https://user-images.githubusercontent.com/77028190/103705259-02359500-4fab-11eb-846c-c4c3aeb59d89.png)

**Comment by ortocurvo** [comment]
[test-malt-error.blend.zip](https://github.com/BlenderNPR/BEER/files/5772899/test-malt-error.blend.zip)
here the file

**Comment by pragma37** [comment]
Hi. Sadly your computer doesn't meet the minimum requirements to run the engine.

See #28 for an explanation.
