### ISSUE TITLE
Sub Category cycling fade persists when working with multiple Node Trees visible at the same time.

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#411]
### Malt version

Node Groups

### Blender version

Blender 3.3

### OS

Windows 10 64x

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

There's two variations of this issue i've found. When adding nodes which have categories and when using the dedicated cycling function.

You need to have two Node Tree windows open at once, both around the same general location in the graph. Add a node with some categories and the fade out will display on both windows while it hovers. It might take some moving the node around in order for it to appear on the screen in both Trees.

![image](https://user-images.githubusercontent.com/31767887/193355407-cac06411-76b7-436e-9b1a-6de4db5aa113.png)

The second variant you have to click the cycling button in one Node Tree, then move around the second window with middle mouse click.

![image](https://user-images.githubusercontent.com/31767887/193355218-af834986-b47c-4a88-92e5-5a0687892fc6.png)

(This might not be an issue with Malt specifically, might be something up with Blender itself, but I figured it'd be best to check here first)

### Attachments

No relevant log/blend

**Comment by pragma37** [comment]
Ooops! I didn't see you assigned this to yourself @Kolupsy.
Take a look at the fix if you have the time.

**Comment by Kolupsy** [comment]
> Ooops! I didn't see you assigned this to yourself @Kolupsy. Take a look at the fix if you have the time.

No worries, I was assigning this to myself because it was my code that was broken and instead of you having to figure out my code (which of course I tried to write as easy-to-understand as possible but still) I was going to find some time do deal with it. But I am not mad at all that you took care of this so quickly xD
