### ISSUE TITLE
Node Properties within Node Groups lose values when linked to other Blend files

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#412]
### Malt version

Node Groups

### Blender version

Blender 3.3

### OS

Windows 10 64x

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

Using the attached blend file, link the "Sphere Material Node Tree" into a new blend file. Create a new material on something, add that node tree to the material.

You might need to recompile the node tree first, as it might not work from the get go after linking. Once the node properties actually display in the test node group, the float property will have changed from 1 to 0. 

### Attachments

[Node groups properties link.zip](https://github.com/bnpr/Malt/files/9691487/Node.groups.properties.link.zip)

**Comment by pragma37** [comment]
I should have seen that one coming.
It's fixed now. Thanks!
