### ISSUE TITLE
Copy node groups to a new node tree leads to a transparent diffuse

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#416]
### Malt version

node-groups-latest

### Blender version

Blender 3.30

### OS

win 11

### Hardware info

intel i7 | gtx 1660

### Issue description and reproduction steps

1. Here is a very simple node group added to main pass color. the node group is a vec3 add of npr diffuse and npr specular. Everything is fine here
![image](https://user-images.githubusercontent.com/36077492/194721937-4924beec-f68c-43e2-bbf9-d307dcfdd554.png)

2. create a new material and a new node tree, assign the new material to the object. 
![image](https://user-images.githubusercontent.com/36077492/194722006-41175e4e-04fc-4623-9913-59cfcefa205f.png)

3. copy the node group to the new material node tree, then connect it to the new mainpass color

![image](https://user-images.githubusercontent.com/36077492/194722078-372c348f-346d-4ee8-b578-fc069cb8ccbb.png)

two issues

first, the object becomes transparent
second, the parameters of the node group disappear

Reload pipelline or restart blender won't help

### Attachments

[Uploading bug.zip…]()

**Comment by pragma37** [comment]
The attachment link doesn't work!

**Comment by HSDSZ** [comment]
> The attachment link doesn't work!

oh sorry, here is the file
[bug.zip](https://github.com/bnpr/Malt/files/9740705/bug.zip)

**Comment by HSDSZ** [comment]
https://user-images.githubusercontent.com/36077492/194760223-87533dcf-4a28-4013-adf9-6d5b73c4a4b4.mp4

**Comment by pragma37** [comment]
The issue was that all-caps names in Malt are considered internal and don't get exposed on the UI. 
So since your node name is "NPR", all parameters were being considered as internal engine stuff.

The internal node name is assigned on node creation and never changes after that, that's why the problem would only show up after a copy.
