### ISSUE TITLE
Property Overrides Do Not Work in Node Groups

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#434]
### Malt version

Node Groups

### Blender version

Blender 3.3

### OS

Windows 10

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

Create a new node group, and add a node within. When attempting to add a property override, the prompt for rendered and preview will show, but nothing will happen upon selecting one of the options.

### Attachments

No relevant log to attatch.

**Comment by pragma37** [comment]
Fixed! 👍
