### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by zangszz** [BlenderNPR/BEER#443]
### Malt version

Release-latest for blender 3,3

### Blender version

Blender 3.3.1

### OS

Windows 11 64bits

### Hardware info

Ryzen 3 2200g 24GB RAM    RX 480 8gb

### Issue description and reproduction steps

i'm new to the malt, to tell you the truth, wanted to test it but, every time I try to use malt, it does not start the cmd block and does not appear the pre-render, it turns on black screen.

(sorry for my bad english)

### Attachments

[malt 2022-11-09(02-29).log](https://github.com/bnpr/Malt/files/9967668/malt.2022-11-09.02-29.log)

**Comment by pragma37** [comment]
This was fixed in the Development version but not in the Release version.

I have just updated the Release version, so If you re-download the addon it should be fixed now.
