### ISSUE TITLE
node group works differently from the separated nodes

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#450]
### Malt version

node-groups-latest

### Blender version

Blender 3.30

### OS

win 11

### Hardware info

intel i7 | gtx 1660

### Issue description and reproduction steps

node group works differently from the separated nodes. please check the video 
https://user-images.githubusercontent.com/36077492/203100461-cded69ae-f2eb-4222-b9a8-b3eef69c4f76.mp4

But when I restart the blend file, the bug disappear, Hope you could get from information from the video

### Attachments

[bug.zip](https://github.com/bnpr/Malt/files/10058218/bug.zip)

**Comment by pragma37** [comment]
I've tried on 2 separate computers (AMD and Nvidia) and can't reproduce it.
Are you using the latest build?

> But when I restart the blend file, the bug disappear

What does this mean exactly? If you recreate the same setup on a new file or if you simply re-open the file?

**Comment by HSDSZ** [comment]
After reopen the file, the strange bug disappear.

I am trying to reproduce this bug. hope to have a stable blend file soon

**Comment by HSDSZ** [comment]
is it because a node group is linked?

I use the latest node group build

Here is the video demo
[2022-11-24-23-59-36.zip](https://github.com/bnpr/Malt/files/10086017/2022-11-24-23-59-36.zip)

**Comment by HSDSZ** [comment]
[Expression.zip](https://github.com/bnpr/Malt/files/10086065/Expression.zip)

Here is the bug file. I can reproduce the bug with this file.
steps to reproduce:
1 unzip
2 open bugfile.blend
3. change the "float" value connected with scale.
4. Connect the nodegroup input bool to the center? socket. Then change the "float" value connected with scale. you will see the difference

**Comment by pragma37** [comment]
Fixed! 👍 

BTW, when you upload reproduction files with textures, try to make sure you pack the images or include them in the zip file.
