### ISSUE TITLE
Malt not displaying after latest AMD GPU driver update

### ISSUE THREAD

**Issue by epicRedHot** [BlenderNPR/BEER#451]
### Malt version

Release

### Blender version

Blender 3.3.1

### OS

Windows 10 64-bits

### Hardware info

AMD FX-4300 Quad-Core | 8 GB RAM | Radeon RX 580

### Issue description and reproduction steps

When attempting to use Malt in the viewport, anything rendered by Malt itself is solid black while anything rendered by Blender on top of it still displays correctly.

This has only started occurring after the most recent driver update for my GPU. This issue also only affects the viewport, as everything else - Malt-related or not - still displays correctly.
![image](https://user-images.githubusercontent.com/76829489/204116445-b969499a-5fc3-470f-9cea-709df04364f4.png)
![image](https://user-images.githubusercontent.com/76829489/204116492-f344a84d-8784-45dd-82f1-082acc9d3b79.png)

### Attachments

[malt 2022-11-27(18-03).log](https://github.com/bnpr/Malt/files/10099500/malt.2022-11-27.18-03.log)

**Comment by pragma37** [comment]
This looks a lot like this issue: https://github.com/bnpr/Malt/issues/393#issuecomment-1247017814

It only happened with the "optional" drivers back then.
Do you know what version are you using (optional or recommended)?
Did you install the drivers yourself or was it an automatic update?

**Comment by epicRedHot** [comment]
Unfortunately my memory is a bit shoddy so I don't quite remember for sure, but I'm fairly certain the driver update was installed automatically - I don't remember my computer doing any "shutdown required" updates within the last week or so.
The driver version with the issue is the one listed in the first image of the initial post, while the last version listed on the updates page is _30.0.13023.4001_ - which was installed back on 3/15/2022.
![image](https://user-images.githubusercontent.com/76829489/204563597-c86dcd4e-cbab-47c0-a75d-f88c8c099522.png)
No other updates, driver or otherwise, have been installed since either the issue started or the most recent driver update back on the 22nd.

**Comment by pragma37** [comment]
I've tried updating the (recommended) drivers and still can't reproduce it.

Could you show a screenshot of your driver system info? Like this:
![imagen](https://user-images.githubusercontent.com/36610999/204883733-08350f31-b02e-4358-9187-d81757013907.png)

**Comment by epicRedHot** [comment]
I'm currently getting a "driver and software do not match" error, so I'll update this comment when I fix this issue.
edit:
Unfortunately, I had to downgrade driver versions as well in order to get the software to work properly, so the info is no longer accurate to the driver version that was having the issues. It did fix the issue of Malt not rendering, however.

**Comment by dibli-goost** [comment]
This is happening to me too, I proceeded to try and rollback drivers to a previous version and it damn near bricked my PC. Had to find my old graphics card to completely uninstall/reinstall AMD software. This is just the recommended drivers, not the optional ones.

![image](https://user-images.githubusercontent.com/31767887/206024251-9143f555-e42d-4913-a039-13a6e48831a8.png)

Malt will not render, black screen. Blender itself seems to be freaking out too, as long as I have a second display active over time the UI gets more and more glitchy. The session log doesn't seem to have anything of note.  Just initializes the pipeline, nothing more.

Pretty sure this is down to a driver problem though. Something up with 31.0.12044.3. Could be something specific to AMD Software: PRO Edition?

**Comment by pragma37** [comment]
> I proceeded to try and rollback drivers to a previous version and it damn near bricked my PC. Had to find my old graphics card to completely uninstall/reinstall AMD software. 

Ouch! If something like that ever happens to you again, you may have an easier time by booting Windows in safe mode and re-installing the drivers from there.

---
Honestly, I can't make any sense of AMD driver version system.
How it's possible that my OpenGL drivers are version 29.10 and yours only 20.10 ?
There's no way I'm 9 major versions ahead of you.

> Pretty sure this is down to a driver problem though.

Yeah, that's for sure. However, if even the recommended drivers have this issue, I'll have to implement a workaround.

> Could be something specific to AMD Software: PRO Edition?

I was able to reproduce this in the regular (non-pro) optional version.
I think it's more likely that RX card drivers are more up-to-date than the integrated graphics ones.

**Comment by pragma37** [comment]
Could you check if this fix works for you?
https://github.com/bnpr/Malt/releases/tag/experimental-workaround-amd-bindless-bug-latest

**Comment by dibli-goost** [comment]
> Could you check if this fix works for you?

Upon installing Malt I get an error and the Malt sub process does not start.

```
Python: Traceback (most recent call last):
  File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderMalt\MaltRenderEngine.py", line 430, in draw
    stats = MaltPipeline.get_bridge().get_stats()
AttributeError: 'NoneType' object has no attribute 'get_stats'
```

**Comment by pragma37** [comment]
Log?

**Comment by dibli-goost** [comment]
> Upon installing Malt I get an error and the Malt sub process does not start.
> 
> ```
> Python: Traceback (most recent call last):
>   File "C:\Users\sexti\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderMalt\MaltRenderEngine.py", line 430, in draw
>     stats = MaltPipeline.get_bridge().get_stats()
> AttributeError: 'NoneType' object has no attribute 'get_stats'
> ```

I had to disable Vertex Color Master to get it to work for some reason, not sure what the connection there is. But anyways this version of Malt isn't fixing the error for me, it's the same as before, no render, no relevant log info. It just inits the pipeline like usual, no errors.

**Comment by pragma37** [comment]
Weird, IIRC that workaround worked for me when I installed the optional AMD drivers.

I've updated the experimental branch to completely disable bindless textures. 
https://github.com/bnpr/Malt/releases/tag/experimental-workaround-amd-bindless-bug-latest
If that still doesn't work then there must be another issue.

**Comment by dibli-goost** [comment]
Still not working for me ☹️

@epicRedHot could you check and see whether or not the experimental branch fixes the issue on the latest drivers? This could just be something unrelated on my end.

----------------

Edit: I was finally able to get older drivers installed again, last working drivers I have on my system is still 22.6.1 (30.0.21023.1015). I'd show the specs in AMD software, but I had to install only the drivers to get it working for some reason.. Anyways.

It's 100% because of the drivers, Malt still works fine on the old version. Using the experimental branch, the log expectedly throws errors about bindless textures being required.
[malt 2022-12-10(13-14).log](https://github.com/bnpr/Malt/files/10200774/malt.2022-12-10.13-14.log)

On the latest drivers (31.0.12044.3), it doesn't report anything. The subprocess starts properly, but it just initializes the pipeline.

If I attempt to open one of my project files with all sorts of stuff going on already, the log will report some extra stuff, but it's all stuff that shows up with both driver versions. Nothing out of the ordinary.

**Comment by pragma37** [comment]
I can reproduce the issue after updating my drivers.

It looks like the issue is caused by returning samplers from a function (Used by the *Parameters > Image* and *Parameters > Color Ramp*).
You don't even need to use them, just having the code there even if it's never used triggers the bug.

I've updated the experimental branch to remove the previous changes and disable the *Image* and *Color Ramp* nodes.
Could you confirm if this version works for you as well?

**Comment by dibli-goost** [comment]
Nope, still isn't working for me.

Could maybe be that the bindless textures thing is still contributing? Maybe it's a combination of it, and samplers returning from a function. Both need to be deactivated.

Loading an actual project. I am getting some errors in the log now. Dunno if these are to be expected:
[malt 2022-12-17(15-18).log](https://github.com/bnpr/Malt/files/10252752/malt.2022-12-17.15-18.log)

**Comment by pragma37** [comment]
Ouch, the shader cache system misled me. Sorry!
It actually needs the bindless textures workaround in addition to disabling those nodes.

I've updated the branch to include both changes AND disable the shader cache system.

Your log has errors because your scene uses the deleted nodes (Color Ramp).

**Comment by dibli-goost** [comment]
Alright yep, that did the trick!

I can still use the older drivers for the time being, assuming a workaround for the sampler thing isn't possible. I use both the color ramp parameters and texture parameters fairly frequently, so I can't just switch to the new drivers just yet.

Glad to find the issue narrowed down.

**Comment by pragma37** [comment]
Yes, this is not a solution, just a confirmation of what's causing the issue.

We may have to re-implement those two nodes as special cases directly in the Blender side. :(

**Comment by DavidRuales** [comment]
This version worked for me, thank you very much @pragma37 
https://github.com/bnpr/Malt/releases/tag/experimental-workaround-amd-bindless-bug-latest

**Comment by pragma37** [comment]
I've updated my drivers today and I've managed to get the full thing working (image parameters too).
Could you test the latest workaround build?
https://github.com/bnpr/Malt/releases/tag/experimental-workaround-amd-bindless-bug-latest

If it works we can merge it into the main branches.

**Comment by DavidRuales** [comment]
Hello @pragma37, what a shame to answer until now, it is working perfectly as before updating. You can merge and I will download it right away

Thank you very much.
