### ISSUE TITLE
Node group type disappear in blender3.4 and new node group release

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#459]
### Malt version

node-groups-latest

### Blender version

Blender 3.40

### OS

win 11

### Hardware info

intel i7 | gtx 1660

### Issue description and reproduction steps

With the latest malt node group release & blender 3.4
There is no malt node type

![image](https://user-images.githubusercontent.com/36077492/208291143-0c05637c-cb41-42a2-9143-eba05e927f1c.png)

### Attachments

[untitled.zip](https://github.com/bnpr/Malt/files/10253527/untitled.zip)

**Comment by pragma37** [comment]
Please, upload the log file.
There's no need to attach a blend file if the error is not file dependent.

**Comment by HSDSZ** [comment]
[malt 2022-12-18(23-57).log](https://github.com/bnpr/Malt/files/10254146/malt.2022-12-18.23-57.log)

**Comment by HSDSZ** [comment]
> Please, upload the log file. There's no need to attach a blend file if the error is not file dependent.
[malt 2022-12-18(23-57).log](https://github.com/bnpr/Malt/files/10254148/malt.2022-12-18.23-57.log)

Here it is. Hope it helps

**Comment by pragma37** [comment]
That's weird. It looks like an issue with PyOpenGL, but it has not been updated for a while, so I don't see why it would break now.

The log says `glGetActiveUniform() takes 3 positional arguments but 8 were given`.
Which is certainly wrong: https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetActiveUniform.xhtml

Your post says Win 11, but the log says Win 10. Which one is true?

Have you tried other versions? (Release/Development)

**Comment by pragma37** [comment]
Actually, glGetActiveUniform takes 7 arguments and Malt passes 7 arguments. No idea where that 8 comes from.

**Comment by HSDSZ** [comment]
> That's weird. It looks like an issue with PyOpenGL, but it has not been updated for a while, so I don't see why it would break now.
> 
> The log says `glGetActiveUniform() takes 3 positional arguments but 8 were given`. Which is certainly wrong: https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetActiveUniform.xhtml
> 
> Your post says Win 11, but the log says Win 10. Which one is true?
> 
> Have you tried other versions? (Release/Development)

It's weird. I use my laptop. Win11 (home) for sure. But when I bought the laptop, it was win 10. Upgrade it to win11 this year

1. For blender 3.4 and node group branch before your last commit, everything is still fine
![image](https://user-images.githubusercontent.com/36077492/208310400-49549224-2d24-46e7-b682-cf99c3f73529.png)
 
2. Blender 3.4 new release version, not working
[release version.txt](https://github.com/bnpr/Malt/files/10254285/release.version.txt)
3. Blender 3.4 new developing version, not working
[develping version.txt](https://github.com/bnpr/Malt/files/10254297/develping.version.txt)

**Comment by pragma37** [comment]
> For blender 3.4 and node group branch before your last commit, everything is still fine

So [this build](https://github.com/bnpr/Malt/suites/9790031815/artifacts/470832108) from [the previous commit](https://github.com/bnpr/Malt/actions/runs/3665697890) works for you ?!?!?

**Comment by HSDSZ** [comment]
> > For blender 3.4 and node group branch before your last commit, everything is still fine
> 
> So [this build](https://github.com/bnpr/Malt/suites/9790031815/artifacts/470832108) from [the previous commit](https://github.com/bnpr/Malt/actions/runs/3665697890) works for you ?!?!?

Oh sorry, not that.

this node group build works for blender 3.4
https://github.com/bnpr/Malt/actions/runs/3665444095
![image](https://user-images.githubusercontent.com/36077492/208441468-cd10d22a-13af-4c52-ab9d-d7b47fcc8b0b.png)

**Comment by HSDSZ** [comment]
Wait. I don't know why, but all of a sudden, all the build works. I will do more tests, if everything is ok, I will close this issue

**Comment by HSDSZ** [comment]
Just, test it. the latest node group build works. 
![image](https://user-images.githubusercontent.com/36077492/208452897-b4c3e996-544a-4ea5-bc4d-fc7467b125f3.png)
