### ISSUE TITLE
Blender crash on creating a new node tree in Render Layer and Render trees.

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#463]
### Malt version

Node Groups

### Blender version

Blender 3.4

### OS

Windows 10

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

Simply create a new node tree somewhere within the Render Layer or Render tree, using the Screen Pass node, or any node with a similar "new node tree function".

Blender crashes soon after, nothing is reported in the malt log. Included the Blender crash log.

### Attachments

[blender.crash.txt](https://github.com/bnpr/Malt/files/10314381/blender.crash.txt)

**Comment by pragma37** [comment]
Are you using the latest Malt version?
This should have been fixed by this commit: 2739016700d8b69b94d4dc2d6b4792d5f7d8611c

**Comment by dibli-goost** [comment]
Ah, my bad, completely forgot to check. Seems to already be fixed.
