### ISSUE TITLE
Render Problem

### ISSUE THREAD

**Issue by tjzzhang** [BlenderNPR/BEER#477]
### Malt version

1.0.0.beta.3.Release

### Blender version

Blender 3.4.1

### OS

Windows-10-10.0.19044-SP0

### Hardware info

Intel i7-4710MQ | GeForce GT 730M

### Issue description and reproduction steps

![无标题](https://user-images.githubusercontent.com/9721816/215098476-3e817e57-7a65-4fc5-b2ba-961e3712dad7.png)

I have load picture as sampler2D and add bloom and shadow on it. It looks ok as shown in the figure above.
But when press F12, it can't render the result, I have changed the picture format, bmp, jpeg, png, and modified the Bit Depth value to 16, 32. It didn't work.

I uploaded the log and source file. 

### Attachments

[malt 2023-01-27(18-05).log](https://github.com/bnpr/Malt/files/10519328/malt.2023-01-27.18-05.log)
[test06.zip](https://github.com/bnpr/Malt/files/10519381/test06.zip)

**Comment by tjzzhang** [comment]
I have tried the develop version, it still can't render the result. The error is same as https://github.com/bnpr/Malt/issues/346, but change the bit depth to 16 or 32 not work.

Blender > Blender 3.4.1 b'blender-v3.4-release' b'55485cb379f7'
Malt > COMPILE MATERIAL : {'msg_type': 'MATERIAL', 'path': 'E:\\BlenderWorkplace\\BenWorkflow\\scenes\\.malt-autogenerated\\test01-Background Shader.screen.glsl', 'search_paths': [], 'custom_passes': []}
Malt > COMPILE MATERIAL : {'msg_type': 'MATERIAL', 'path': 'E:\\BlenderWorkplace\\BenWorkflow\\scenes\\.malt-autogenerated\\test01-Bloom Material Node.screen.glsl', 'search_paths': [], 'custom_passes': []}
Malt > COMPILE MATERIAL : {'msg_type': 'MATERIAL', 'path': 'E:\\BlenderWorkplace\\BenWorkflow\\scenes\\.malt-autogenerated\\test01-Default Mesh.mesh.glsl', 'search_paths': [], 'custom_passes': []}
Malt > COMPILE MATERIAL : {'msg_type': 'MATERIAL', 'path': 'E:\\BlenderWorkplace\\BenWorkflow\\scenes\\.malt-autogenerated\\test01-Picture.mesh.glsl', 'search_paths': [], 'custom_passes': []}
Malt > COMPILE MATERIAL : {'msg_type': 'MATERIAL', 'path': 'E:\\BlenderWorkplace\\BenWorkflow\\scenes\\../shaders/SVG/test01.mesh.glsl', 'search_paths': [], 'custom_passes': []}
Malt > LOAD MESH : {'msg_type': 'MESH', 'name': 'MESH_Cube', 'data': None}
Malt > LOAD MESH : {'msg_type': 'MESH', 'name': 'MESH_Cube.001', 'data': None}
Malt > LOAD MESH : {'msg_type': 'MESH', 'name': 'MESH_Plane.001', 'data': None}
Malt > LOAD TEXTURE : {'msg_type': 'TEXTURE', 'buffer': <Bridge.ipc.SharedBuffer object at 0x000001CA982B8CA0>, 'name': 'drawTest01_00000.png.001', 'resolution': (2048, 2048), 'channels': 4, 'sRGB': True}
Malt > SETUP RENDER : {'msg_type': 'RENDER', 'viewport_id': 1, 'resolution': (1304, 417), 'scene': <Malt.Scene.Scene object at 0x000001CA982B8AF0>, 'scene_update': True, 'new_buffers': {'__resolution': (1304, 417), '__AOVs': {}, 'COLOR': <Bridge.ipc.SharedBuffer object at 0x000001CA982B8400>}, 'renderdoc_capture': False}
Malt > SETUP RENDER : {'msg_type': 'RENDER', 'viewport_id': 1, 'resolution': (1304, 417), 'scene': <Malt.Scene.Scene object at 0x000001CA98261810>, 'scene_update': True, 'new_buffers': None, 'renderdoc_capture': False}
Malt > Texture Uniform SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_POINT not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_POINT not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_POINT not found
Malt > Texture Uniform IN_LIGHT_CUSTOM_SHADING not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_POINT not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_POINT not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_DEPTH_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_ID_POINT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SPOT not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_SUN not found
Malt > Texture Uniform TRANSPARENT_SHADOWMAPS_COLOR_POINT not found
Malt > Texture Uniform IN_LIGHT_CUSTOM_SHADING not found
Malt > STATS: Viewport (1):
Resolution : (1304, 417)
Sample : 1 / 9
Sample Time : 204.148 ms
Total Time : 0.204 s
Latency : 1 frames
Max Latency : 1 frames

[malt 2023-01-30(09-25).log](https://github.com/bnpr/Malt/files/10531548/malt.2023-01-30.09-25.log)

**Comment by pragma37** [comment]
I can't reproduce the issue on my main computer, but I could reproduce it on my laptop.

I'm not sure why it happens yet (the opengl library we use seems to fail for no good reason), but could you check if enabling this option helps?

![imagen](https://user-images.githubusercontent.com/36610999/215907184-5bd72721-abca-43da-80b5-b7d07d48b335.png)

**Comment by pragma37** [comment]
BTW, you should disable the `Debug Mode` in the addon options.

**Comment by tjzzhang** [comment]
It's amazing. After enabling the "Lock interface", there is no problem with rendering. 
Thanks

**Comment by pragma37** [comment]
Nice! :)

I've added an update to the [Development Version](https://github.com/bnpr/Malt/releases/tag/Development-latest) that should fix the issue without having to enable the `Lock Interface` option.
Could you check if it works for you too?

**Comment by tjzzhang** [comment]
Yes, it works well, good job!
