### ISSUE TITLE
Blender crashes when duplicate malt node

### ISSUE THREAD

**Issue by kozatt0** [BlenderNPR/BEER#480]
### Malt version

Release 

### Blender version

Blender 3.4.1

### OS

Windows 11 64 bits

### Hardware info

Intel i5|16GB RAM| Nvidia RTX 2060 GB

### Issue description and reproduction steps

The error occurs when you duplicate or copy more than 2 malt nodes, it also occurs when you duplicate the malt node tree as long as it has more than 2 nodes.

The version of blender that I use is 3.4.1 and malt is dated 5 Jan | Latest

### Attachments

[example.zip](https://github.com/bnpr/Malt/files/10719682/example.zip)
[malt 2023-02-13(04-18).log](https://github.com/bnpr/Malt/files/10719683/malt.2023-02-13.04-18.log)

**Comment by kozatt0** [comment]
https://user-images.githubusercontent.com/40680159/218408202-ea764a14-c3c4-4e17-bc03-4e0ba3d40b9f.mp4

**Comment by pragma37** [comment]
This one got introduced in 3.4.1.
I need to look into the details, but for now you can revert to Blender 3.4.0.

**Comment by Jenssons** [comment]
So i don't make a Dupe post i have the same problem but im on 3.4.0 with the newest version of malt and it crashes when i try to copy the material or to many nodes at once

**Comment by kozatt0** [comment]
Yeah. i still have the same problem with 3.4.0 so basically i had to back to 3.3 lts.

**Comment by pragma37** [comment]
Could you try with 3.4.1 and the latest Malt version?

**Comment by Jenssons** [comment]
i was using the newest version of blender and malt before trying 3.4.0 it was the same issue

**Comment by pragma37** [comment]
I can't reproduce it myself.
What version of Malt are you using (Release/Development)?

Could you post the Malt log and the Blender crash report?

You mention it crashes when duplicating too many nodes at once, does it mean it doesn't crash when duplicating a low number of nodes?

**Comment by kozatt0** [comment]
These are some tests I did. In the first one, with just a diffuse node, the program doesn't crash.
This works if you duplicate using [ctrl+c] and [ctrl+v] or using the duplicate node option, however when using duplicate node for some reason those connecting the nodes either lose their connection or are misconnected. 
But when using [shift + d] the program crashes

https://user-images.githubusercontent.com/40680159/223865912-c1ebf3af-c058-4173-81e0-6a51c15f2a75.mp4

the second test which is the one where the error always occurs.
is when another diffuse node is mixed with a layer node and another diffuse node. in any of these cases. either [ctrl+c]+[ctrl+v] or [shift+d] or duplicate node. the program crashes.

https://user-images.githubusercontent.com/40680159/223866681-ab745b1b-4067-41cf-abe9-f7e42f2cb390.mp4

i might suspect that the error is related to what i showed in the first test. that when the nodes are duplicated they are unlinked

Here I leave the system specifications

Malt version
Feb 14 2023

Blender version
Blender 3.4.0

OS
Windows 11 64 bits

Hardware info
Intel i5|16GB RAM| Nvidia RTX 2060 GB

Here the blend file and the log

hope it helps!
[maltbuild3.4.zip](https://github.com/bnpr/Malt/files/10925790/maltbuild3.4.zip)
[malt 2023-03-08(19-23).log](https://github.com/bnpr/Malt/files/10925792/malt.2023-03-08.19-23.log)

**Comment by kozatt0** [comment]
I should add that this error doesn't occur in blender 3.3.3 LTS


https://user-images.githubusercontent.com/40680159/223870409-387cae18-af48-4034-93c1-012dc6b5eee6.mp4

**Comment by Jenssons** [comment]
> I can't reproduce it myself. What version of Malt are you using (Release/Development)?
> 
> Could you post the Malt log and the Blender crash report?
> 
> You mention it crashes when duplicating too many nodes at once, does it mean it doesn't crash when duplicating a low number of nodes?

ill work on this after i finish my live stream haha

**Comment by Jenssons** [comment]
[malt 2023-03-09(06-54).log](https://github.com/bnpr/Malt/files/10928662/malt.2023-03-09.06-54.log)


here is my log
if you need anything else please ask im even happy to test out things for you also

**Comment by pragma37** [comment]
Could you check Blender 3.5 with the latest Development version?
https://github.com/bnpr/Malt/releases/tag/Development-latest

**Comment by Jenssons** [comment]
i didnt crash!!!! and i used a HUGE node tree, lets see how kozatt0 blender reacts

**Comment by pragma37** [comment]
Awesome! Thanks for the quick answer. 😃

**Comment by kozatt0** [comment]
Funciona!

Nicee..
its works!

even more so blender 3.5 had a lot of performance improvements, very excited to try it with malt now knowing it works
Thank you!

pd: mucha suerte con los que estas implementando en eevee next :)

https://user-images.githubusercontent.com/40680159/228975420-88d0afd0-c018-4968-9471-f145d84eab40.mp4

**Comment by pragma37** [comment]
Great!
I'm going to merge it into the Release branch as well, then.

> pd: mucha suerte con los que estas implementando en eevee next :)

Gracias!
