### ISSUE TITLE
Windows 11 compatibility

### ISSUE THREAD

**Issue by mkolcun** [BlenderNPR/BEER#482]
### Malt version

1.0.0 beta 3 Release

### Blender version

3.4.1 alpha

### OS

Windows 11

### Hardware info

AMD Ryzen 9 3900X; 32GB; GeForce RTX 2080Ti, GeForce 2060

### Issue description and reproduction steps

Not rendering anything in viewport, in Material shading / render.  Working with same HW on Windows 10 -64

### Attachments

![image](https://user-images.githubusercontent.com/84317238/219043241-f2914196-feda-4e09-9286-c4d94aba5a5a.png)

**Comment by pragma37** [comment]
Please, upload the log file.
I can't do anything with that info.
https://github.com/bnpr/Malt/blob/Development/.github/ISSUE_TEMPLATE/bug_report.yml

**Comment by mkolcun** [comment]
Could you provide me more info of which log, from where to upload, too?

**Comment by pragma37** [comment]
The info is on the bug report template (I linked to it my previous comment).
Specifically:

### Attachments
- The **Log file** from the Blender session where the bug happened.
You can find it in *Preferences > Addons > BlenderMalt > Open Session Log* or search for it in your system temporary folder.
- A zipped **.blend file** with a minimal example to reproduce the error. *(Unless the error is not file dependent)*
> Don't copy/paste the *Log* text. Drag and drop the files to upload them.
