### ISSUE TITLE
Textures turning gray after crash

### ISSUE THREAD

**Issue by DonKon66** [BlenderNPR/BEER#492]
### Malt version

1.0.0.beta.3.release

### Blender version

3.4.1

### OS

Windows 11 64 bits

### Hardware info

Intel i5-9400F | 16GB RAM | GeForce GTX 1660 Ti

### Issue description and reproduction steps

My Blender crashend after I tried to render a Video. I haven't saved my file so I loaded an autosave, but in "rendered" and "material previev" mode everything was grayed out and background-colored, as if it weren't even there.
[Szene1.zip](https://github.com/bnpr/Malt/files/11112921/Szene1.zip)

### Attachments

[BlenderCrash.txt](https://github.com/bnpr/Malt/files/11112874/BlenderCrash.txt)

**Comment by pragma37** [comment]
The scene is failing to load because of an object called `Icosphere.009`, which seemingly got corrupted and is storing wrong material indices (that might be why Blender crashed?).
If you hide that object or delete its material **slot** and create a new one it loads fine. 👍
