### ISSUE TITLE
Malt Render not Displaying in AMD Driver latest Update

### ISSUE THREAD

**Issue by NipXray** [BlenderNPR/BEER#495]
### Malt version

Release

### Blender version

Blender 3.5.0

### OS

Windows 10 64 bits

### Hardware info

Xeon X3450 18 GB Ram AMD RX 580

### Issue description and reproduction steps

Driver AMD Adrenalin Edition Version 23.4.1 - Blender 3.5.0 Render using malt 3D Viewport became totally Black, other Render Engine is fine, when downgrade Driver Version can't open Blender 3.5.0 close on Launch.

### Attachments

![image](https://user-images.githubusercontent.com/120429580/232787859-8c269b20-1b6c-47b5-9a24-e1f80975ab9c.png)

**Comment by NipXray** [comment]
Manual Installing Driver, Installing using AMD Recommended option

**Comment by DavidRuales** [comment]
I have the same problem

**Comment by DeltishEffort** [comment]
Hello, I also have noticed something similar happening.
[my system info](https://pastebin.com/raw/XDdBeJAy)
[Malt Session Log Output](https://pastebin.com/raw/mHVS9haK)

Doing a manual install following the [Setup for development instructions](https://github.com/bnpr/Malt/blob/Development/docs/Setup-BlenderMalt-for-Development.md) makes things render properly again for me.

**Comment by NipXray** [comment]
i don't understand how to install Malt for development version i have tried following the instruction and still the malt no showing in the Addon List, are my command is the wrong one?

"E:\Blender\3.5\3.5\python\bin\python.exe E:\Blender Addon\Malt-Development\scripts\setup_blender_addon.py E:\Blender Addon\Malt Dev"

i m sorry, i m totally beginner at this

**Comment by DeltishEffort** [comment]
> 

the command I use looks like this for me
```shell
& "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\bin\python.exe" "C:\Users\cptpa\Projects\malt\scripts\setup_blender_addon.py" --scripts-folder "C:\Users\cptpa\Projects\ProgramData\Blender Scripts"
```

**Comment by DeltishEffort** [comment]
> i don't understand how to install Malt for development version i have tried following the instruction and still the malt no showing in the Addon List, are my command is the wrong one?
> 
> "E:\Blender\3.5\3.5\python\bin\python.exe E:\Blender Addon\Malt-Development\scripts\setup_blender_addon.py E:\Blender Addon\Malt Dev"
> 
> i m sorry, i m totally beginner at this

no problem :), hopefully we'll figure it out

I used ```git clone https://github.com/bnpr/malt``` to clone the dev repo to my Projects folder and I have a Blender Scripts folder for scripts

the command I'm using looks like this for me in powershell because I have spaces in my folder names

```shell
& "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\bin\python.exe" "C:\Users\cptpa\Projects\malt\scripts\setup_blender_addon.py" --scripts-folder "C:\Users\cptpa\Projects\ProgramData\Blender Scripts"
```
Make sure your Preferences > File Paths > Scripts is pointing to the folder you provided as well
![image](https://user-images.githubusercontent.com/41149511/233024336-6daa66bd-50ba-4224-a2b0-436d13098b7e.png)

**Comment by NipXray** [comment]
Ah, thank you soo much, now it fixed... and i figure out other way for who have the same problem to download the development version.

https://github.com/bnpr/Malt/releases/tag/Development-latest

Works for AMD driver Adrenalin Edition 23.4.1

![image](https://user-images.githubusercontent.com/120429580/233036512-692294f3-e8d1-492f-aad8-d8514e0343ff.png)

**Comment by pragma37** [comment]
This issue was discussed here too: https://github.com/bnpr/Malt/issues/451

I implemented the fix in the Development version, but not in the Release version.
Since it seems to be working fine I just committed the fix to the Release version as well.
