### ISSUE TITLE
Does not install on Linux KDE Neon

### ISSUE THREAD

**Issue by Gaonirico** [BlenderNPR/BEER#5]
I have followed the installation instructions but the addon is not listed, even though the files do appear in the Blender 2.9 scripts folder. I have tried using Blender with administrator rights using the kdesu command indicated on some websites but the result is the same.Maybe it only works on Windows or do I need to download certain dependencies on Linux for it to work?

**Comment by pragma37** [comment]
It should work, there are people running it on Linux. Do the terminal prints any errors?

The addon is called BlenderMalt, btw. Maybe you are searching for BEER ?

Try to install it on a portable version of blender, that way you don't need super user rights.
https://www.blender.org/download/Blender2.83/blender-2.83.3-linux64.tar.xz/

**Comment by Gaonirico** [comment]
My bad, sorry. Turns out I had downloaded a old version of the BlenderMalt so it didn't work for me. Now i downloaded the latest version and it works great. I like that it is so fast to visualize drawing lines on even complex models. But testing I have noticed that when trying to render with Beer in Blender version 2.91 the result is a slightly blurred image. In Blender versions 2.83 and 2.90, when trying to render the program closes spontaneously. Here I leave a screenshot of Blender where the lines are correctly previewed or another image where the render gives a blurred result
![Beer Capture](https://user-images.githubusercontent.com/66271375/89240356-4377e200-d5d2-11ea-8c9d-276c9f11239a.png)
![Beer Render](https://user-images.githubusercontent.com/66271375/89240371-4ecb0d80-d5d2-11ea-87c8-3c256659c9ed.jpg)

**Comment by pragma37** [comment]
The blur issue should be fixed in the latests versions.
F12 rendering doesn't work on Blender 2.83 unless you download [this version](https://github.com/pragma37/Blender-NPR/actions/runs/179205904), but It shouldn't crash Blender anyway.
And on somewhat recent 2.9 versions it should work. If Blender crashes when doing F12 rendering the terminal should be printing some errors. If you show me those I can take a look at it.

**Comment by Gaonirico** [comment]
I downloaded the latest version of blender 2.90 today and the program no longer closes when trying to render. The only problem I have seen now is that when you try to edit a mesh preview with Malt Blender freezes graphically until after a few seconds it closes instantly. Here I leave the text displayed in the terminal (EditMode_Terminal_blender.crash) and the bug file generated by the Blender program itself (EditMode_TemporalFile_blender.crash)

[EditMode_Terminal_blender.crash.txt](https://github.com/BlenderNPR/BEER/files/5031711/EditMode_Terminal_blender.crash.txt)

[EditMode_TemporalFile_blender.crash.txt](https://github.com/BlenderNPR/BEER/files/5031714/EditMode_TemporalFile_blender.crash.txt)

**Comment by pragma37** [comment]
Could you try the last version and tell me if Blender still freezes in edit mode?
