### ISSUE TITLE
Material System is not working

### ISSUE THREAD

**Issue by jaxxcoder** [BlenderNPR/BEER#501]
### Malt version

Release

### Blender version

Blender 3.5

### OS

Windows 10

### Hardware info

Intel Pentium | 4gb ram

### Issue description and reproduction steps

Your whole malt node editor is not working on my system

### Attachments

Try to fix it . I really like the style of your render engine .

**Comment by pragma37** [comment]
Sorry, but "it doesn't work, please fix it" is not even near enough info to do anything.
If you want me to look into it, open a new issue and this time fill it with the required information.
