### ISSUE TITLE
Depth Width Lines generated incorrectly in Screen Shader.

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#504]
### Malt version

Node Groups

### Blender version

Blender 3.5

### OS

Windows 10

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

When using the Line Width or Line Detection nodes in a screen pass. Depth Width lines are not generated correctly.

For comparison:

When Depth Width is used in a mesh shader.
![image](https://github.com/bnpr/Malt/assets/31767887/ce497a22-ab29-4060-bc7e-34e2f0e2cabc)

When Depth Width is used in a screen shader.
![image](https://github.com/bnpr/Malt/assets/31767887/832b956c-6952-40e4-a6d6-75bc0f0547aa)

Honestly kind of embarrassed that I didn't notice this sooner. Since I've been generating lines in the screen shader directly for ages now. I'd guess the issue is being caused by normal depth not being properly passed into Line Detection when in the screen shader.

### Attachments

[Line Width Screen Pass bug.zip](https://github.com/bnpr/Malt/files/11808157/Line.Width.Screen.Pass.bug.zip)

**Comment by pragma37** [comment]
Fixed! Thanks for the report.
