### ISSUE TITLE
Malt Settings label appears in non-mesh and light data tabs when data block is pinned.

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#508]
### Malt version

Node Groups

### Blender version

Blender 3.6

### OS

Windows 10

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

If you pin the "data" tab, an empty Malt Properties label will appear in the tab even when it's not relevant. A duplicate one also seems to generate.

### Attachments

![image](https://github.com/bnpr/Malt/assets/31767887/9a244c2f-4cd9-441a-85c1-eb0a4b864a99)

**Comment by pragma37** [comment]
Fixed, thanks for the report.
It's quite weird the way the pinned UI works, even some of the built-in panels don't work properly. 🤔
