### ISSUE TITLE
Malt nodes not working properly

### ISSUE THREAD

**Issue by rosstheblenderanimator** [BlenderNPR/BEER#522]
### Malt version

latest

### Blender version

Blender 3.6.4

### OS

Windows 11 64

### Hardware info

AMD Ryzen 7 3800X 8-Core NVIDIA GeForce GTX 1650 16gb ram

### Issue description and reproduction steps

HI the mesh shader is red and I can't add any nodes. And I have downloaded the latest version and my GPU supports greater than Open GL 4.1 and ask the Beer-Malt channel and the GitHub Malt forum. Also the tiny black window does not show up.
![Screenshot 2023-09-28 145717](https://github.com/bnpr/Malt/assets/146353254/808f2c0d-7405-4697-af05-e766af6375bc)

### Attachments

[untitled.zip](https://github.com/bnpr/Malt/files/12753874/untitled.zip)

**Comment by DeltishEffort** [comment]
After some troubleshooting on discord we discovered that the problem was Blender being run as a Windows Store App. Running a regular Blender install from the Blender site works as expected 💪
[malt_2023-09-2910-34.log](https://github.com/bnpr/Malt/files/12769424/malt_2023-09-2910-34.log)

**Comment by eballeste** [comment]
nice job @DeltishEffort !!!

@rosstheblenderanimator please close this issue if your problem has been resolved

**Comment by pragma37** [comment]
Closing. Thanks @DeltishEffort !
