### ISSUE TITLE
Viewport Render Image doesn't show anything besides the gizmo

### ISSUE THREAD

**Issue by xxkq** [BlenderNPR/BEER#524]
### Malt version

1.0.0.beta.3.Release

### Blender version

Blender 3.5.1

### OS

Windows 10 22H2

### Hardware info

Intel i7-7700k | 16 GB RAM | Nvidia RTX 2070 Super

### Issue description and reproduction steps

![image](https://github.com/bnpr/Malt/assets/17611340/d21836b2-dc14-4c85-a425-b8312b7b7df0)

![image](https://github.com/bnpr/Malt/assets/17611340/435428ed-4878-4a64-8b89-ec66fe35d603)

**Reproduction Steps**
1. Make a new scene, change render engine to Malt
2. Change Viewport Shading to Rendered Preview
3. Try making a rendered view of the viewport by View -> Viewport Render Image. The resulting image should be blank similar to the screenshot above

### Attachments

[malt 2023-10-06(11-43).log](https://github.com/bnpr/Malt/files/12826975/malt.2023-10-06.11-43.log)

**Comment by pragma37** [comment]
Hey, sorry for the late reply.

This is just the way it is. 
There's no way for external renderers to support this feature, not even Cycles does.
