### ISSUE TITLE
the NPR Specular node does not work as expected on a default plane/cube with flat shading

### ISSUE THREAD

**Issue by nikeizawa** [BlenderNPR/BEER#527]
### Malt version

Development

### Blender version

Blender 3.6.4

### OS

Windows 10 64 bits

### Hardware info

i3-3220 | 4GB | HD6670 2GB

### Issue description and reproduction steps

The specular should be smooth
this issue doesn't happen when using the internal Specular Shading node

NPR Specular:
![image](https://github.com/bnpr/Malt/assets/148445199/ca392f87-560a-43a5-8f5a-da1c63d9b5b6)

Specular Shading:
![image](https://github.com/bnpr/Malt/assets/148445199/afd2f5dd-4450-4dbe-8d0b-dc0b66465fcb)

Reproduction Steps:
1.Create a new file
2.Add a plane or a cube
3.use NPR Specular on the object
4.Add any light source

### Attachments

[malt 2023-10-19(15-59).log](https://github.com/bnpr/Malt/files/13040992/malt.2023-10-19.15-59.log)
[flat_spec.zip](https://github.com/bnpr/Malt/files/13041064/flat_spec.zip)

**Comment by pragma37** [comment]
Fixed. Thanks for the report.
It was an issue with radial tangents (which the specular node uses by default) when the normal is exactly Z-up.
