### ISSUE TITLE
malt crash in blender 4.0 (latest nodegroup version)

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#532]
### Malt version

node-groups-latest

### Blender version

Blender 4.0

### OS

win 11

### Hardware info

intel i5-12400F  RTX3060Ti

### Issue description and reproduction steps

blender crash when you render

https://github.com/bnpr/Malt/assets/36077492/41e1df5d-bd58-4353-8eaf-29d67dc48a6b

### Attachments

[malt 2023-11-16(22-24).zip](https://github.com/bnpr/Malt/files/13378770/malt.2023-11-16.22-24.zip)

blend file independent

**Comment by pragma37** [comment]
Should be fixed by f81a3c5.
Thanks for the report!
