### ISSUE TITLE
Latest node group version has no windows/linux version for installing

### ISSUE THREAD

**Issue by HSDSZ** [BlenderNPR/BEER#536]
### Malt version

node-groups-latest

### Blender version

Blender 4.0

### OS

win 11

### Hardware info

intel i5-12400F  RTX3060Ti

### Issue description and reproduction steps

Latest node group version has no windows/linux version for installing.
It has only source code

### Attachments

No file needed

**Comment by pragma37** [comment]
Sometimes the automatic releases are tagged as a "Draft", which makes the binaries unavailable.
I have no idea why, though.

Should be fine now.
