### ISSUE TITLE
UV Map order is messed up when using Join Geometry Node

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#565]
### Malt version

Node Groups

### Blender version

Blender 4.1.1

### OS

Windows 10

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | NVIDIA GeForce GTX 1080 Ti 

### Issue description and reproduction steps

The Join Geometry node in Geometry Nodes messes up the order of UVs in Malt. You do have to actually join some geometry, doesn't do anything if you just try to pass one thing through. You also need to have multiple UV maps on the mesh.

Here, I'm just passing the geometry through the join geometry. Works as expected.
![image](https://github.com/bnpr/Malt/assets/31767887/1f65ffcb-e6a2-4418-88ab-ee13456b1561)

Here, I'm adding a duplicate to the join, the UV index no longer corresponds to the correct map.
![image](https://github.com/bnpr/Malt/assets/31767887/b639d51f-6f9e-4fce-89a6-01132dea53af)

I'm guessing Geometry Nodes is reordering the list of UV Maps when joining, it appears to do so in the spreadsheet as well, but since the default node editors just refer to UV Maps by name, I'm not sure it would really be a bug for Blender itself?

### Attachments

[uvorder.zip](https://github.com/user-attachments/files/15974133/uvorder.zip)

**Comment by pragma37** [comment]
> I'm guessing Geometry Nodes is reordering the list of UV Maps when joining, it appears to do so in the spreadsheet as well, but since the default node editors just refer to UV Maps by name, I'm not sure it would really be a bug for Blender itself?

This seems to affect exporters as well (exporting a gltf of the mesh and importing it again breaks the UV ordering).
So I'd say it's fair to report it in the Blender bug tracker.

If the issue gets rejected, reopen this so we can add a workaround.
