### ISSUE TITLE
 Main project file crashes when opening. But previous file version does not

### ISSUE THREAD

**Issue by rosstheblenderanimator** [BlenderNPR/BEER#572]
### Malt version

Release

### Blender version

Blender 4.2

### OS

Windows 11 64

### Hardware info

AMD Ryzen 7 3800X 8-Core NVIDIA GeForce GTX 1650 16gb ram

### Issue description and reproduction steps

But when I open the previous version any other malt related file it also works. I tried restarting my computer did not work. I uninstalled malt did not work and then reinstalled the previous version of blender did not work either. I took this screenshot before it close.
![Screenshot 2024-08-06 174559](https://github.com/user-attachments/assets/70062203-1add-43f5-b632-38a05266bcb6)

### Attachments

https://1drv.ms/u/s!Avu4kI9oS573g-REsbM_3MukbsYGfA?e=hdjbLn

**Comment by rosstheblenderanimator** [comment]
I was able to recover it using the blend1 file

**Comment by rosstheblenderanimator** [comment]
I tried to open the file earlier on today and it crashed before it could open. I then recovered the file using Blend1 and I redid some of the work that was not recovered which was not much. I then saved my work, closed the file and then restarted my computer. I opened the file and it worked. Later on today I closed the file and then tried re opening a bit later and it did not work.

**Comment by rosstheblenderanimator** [comment]
I can't recover the file with the blend1 file because when I drag it into blender and click open it crashes.

**Comment by rosstheblenderanimator** [comment]
It happened again now I have to redo some work again.

**Comment by pragma37** [comment]
This is the same issue as #560.
So I'm closing it as a duplicate.
