### ISSUE TITLE
Color may not be displayed

### ISSUE THREAD

**Issue by pragma37** [BlenderNPR/BEER#581]
### Discussed in https://github.com/bnpr/Malt/discussions/577

<div type='discussions-op-text'>

<sup>Originally posted by **41014C** September  3, 2024</sup>
I am a Japanese creator who has been using Malt since April this year.

Sometimes I can only enter numerical values for node color items such as AlphaBlend. Is this a bug? I have copied a node that is displayed from a node that is displayed from a node that is displayed from a node that is displayed from a node.
I would like to know how to fix it.

![IMG_8349](https://github.com/user-attachments/assets/f5e7372b-d2e5-41ed-a5de-f18e72c3fa75)
![IMG_8350](https://github.com/user-attachments/assets/b4b8b265-4d89-411c-8174-92236ccdb38d)
</div>

**Comment by pragma37** [comment]
Hello @41014C. Yes, this is a bug, so I converted it to an issue.

Could you upload a file where I can reproduce this error?

**Comment by 41014C** [comment]
Hello.Miguel Pozo.
Thank you for your reply.
I attach the data in question.
Best regards.

2024年9月15日(日) 1:34 Miguel Pozo ***@***.***>:

**Comment by Dereuz24** [comment]
> Hello @41014C. Yes, this is a bug, so I converted it to an issue.
> 
> Could you upload a file where I can reproduce this error?

I was going to create a new issue when I found this out but luckily just saw this post. The steps that reproduce this bug consistently on my end are:

- Create new material
- Create new node
- Add RGBA color or whatever
- Add Depth Offset output
- Add Float
- Connect modify


After the Depth offset output is introduced into a node tree none of the RGB, RGBA parameters or any color entry in the rest of the nodes work.

The mechanism for that might be the same as when I've seen it happening randomly

**Comment by pragma37** [comment]
@Dereuz24 Like this?
![imagen](https://github.com/user-attachments/assets/5d1490b6-951a-4e68-8ac4-8f3b23539522)
I can't repro it.

**Comment by Teelron** [comment]
I've been able to make it happen consistently by adding a Depth Offset node to a new malt material before any other nodes. Just adding the depth offset causes many other nodes to have these problems.

1.  Open new general file
2. Switch to Malt renderer
3. Give default cube malt node tree
4. Add depth offset output node
5. Add RGB color parameter

**Comment by pragma37** [comment]
@Teelron Thanks! I can repro following those steps.
