### ISSUE TITLE
Freeze on Divide by Zero in shader

### ISSUE THREAD

**Issue by Lateasusual** [BlenderNPR/BEER#8]
```glsl
@MAIN_PASS_PIXEL_SHADER
{
  OUT_COLOR = vec4(1 / 0.0);
}
```
Using this code in a Malt shader causes blender to lock up completely for 5-10 seconds, render the UI once and then lock again while rendering again. This eventually causes a full system-wide graphics driver crash.

Tested on Manjaro Linux with Nvidia drivers.

**Comment by pragma37** [comment]
I can't reproduce this on my end. (gtx 950 on Windows 10)
This looks like a driver bug.

It may be related to Blender Color Management ?
What happens if you comment out this line ?
https://github.com/BlenderNPR/BEER/blob/master/BlenderMalt/MaltRenderEngine.py#L240

**Comment by Lateasusual** [comment]
Forgot to close this, was found to be a driver bug.
