### ISSUE TITLE
Render occurs in a separate window?

### ISSUE THREAD

**Issue by HelixD** [BlenderNPR/BEER#96]
For some reasons, the render doesn't happen in blender itself but in another dedicated windows and it's very unconvenient to work with D:

![maltt](https://user-images.githubusercontent.com/86878986/124353951-d289e180-dc09-11eb-9ae1-c59b098a156b.png)

I currently use Blender 2.93 and 3.0 beta on a laptop with both integrated intel graphics and a GTX 960m.

Thanks for your assistance!

**Comment by Paperaincoat** [comment]
Yes, I also experience the exact same thing and I do not really know why :(

**Comment by pragma37** [comment]
Hi! Sorry for the late reply,  I'm currently on vacation.

You have downloaded the [draw-to-window branch](https://github.com/bnpr/Malt/releases/tag/draw-to-window-latest).

Please, read the [install instructions](https://github.com/bnpr/Malt/releases/tag/draw-to-window-latest). (Note that nodes are currently only available in the Development branch)
