### ISSUE TITLE
Unable to install the Malt addon into Blender

### ISSUE THREAD

**Issue by Paperaincoat** [BlenderNPR/BEER#97]
I have downloaded the Malt addon and added the config folder. However, I couldn't have the addon installed into Blender. I tried deleting the config folder which somehow by doing so the addon can get installed, but then it just doesn't show anything in the render mode and there are also no options in the material tab. Can you please help? 

For clarifications, I use Windows and the Blender version is currently 2.92.

**Comment by pragma37** [comment]
Answered in #96
